using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class ChargeSeedBuilder : ISeedBuilder
    {
        public int Priority => 130;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<Charge>().HasData(
                new Charge { Id = 1, EnrollmentId = 1, Status = ChargeStatus.Paid, SchoolNameSnapshot = "Northview Secondary School", CourseCodeSnapshot = "CRS-2026-A1B2C3D", CourseNameSnapshot = "Quantitative Problem Solving", CourseDescriptionSnapshot = "Applied numeracy and structured problem-solving for academic pathways.", CourseStartDateSnapshot = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 12, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 100m, MiscFeeAmountSnapshot = 10m, GstAmountSnapshot = 10m, TaxRateSnapshot = 0.09m, GrossAmount = 120m, SubsidyAmount = 0m, NetAmount = 120m, PaidAmount = 120m, RemainingAmount = 0m, CreatedAt = createdAt },
                new Charge { Id = 2, EnrollmentId = 2, Status = ChargeStatus.Unpaid, SchoolNameSnapshot = "Eastbridge Secondary School", CourseCodeSnapshot = "CRS-2026-B2C3D4E", CourseNameSnapshot = "Software Foundations with C#", CourseDescriptionSnapshot = "Core programming concepts, debugging, and application structure.", CourseStartDateSnapshot = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 12, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 115m, MiscFeeAmountSnapshot = 12m, GstAmountSnapshot = 13m, TaxRateSnapshot = 0.09m, GrossAmount = 140m, SubsidyAmount = 0m, NetAmount = 140m, PaidAmount = 70m, RemainingAmount = 70m, CreatedAt = createdAt },
                new Charge { Id = 3, EnrollmentId = 3, Status = ChargeStatus.Unpaid, SchoolNameSnapshot = "Westhaven Secondary School", CourseCodeSnapshot = "CRS-2026-C3D4E5F", CourseNameSnapshot = "Professional Communication Lab", CourseDescriptionSnapshot = "Practical writing, presentation, and workplace communication skills.", CourseStartDateSnapshot = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 130m, MiscFeeAmountSnapshot = 15m, GstAmountSnapshot = 15m, TaxRateSnapshot = 0.09m, GrossAmount = 160m, SubsidyAmount = 0m, NetAmount = 160m, PaidAmount = 140m, RemainingAmount = 20m, CreatedAt = createdAt },
                new Charge { Id = 4, EnrollmentId = 4, Status = ChargeStatus.Paid, SchoolNameSnapshot = "Southpoint Secondary School", CourseCodeSnapshot = "CRS-2026-D4E5F6G", CourseNameSnapshot = "Sustainability Science Workshop", CourseDescriptionSnapshot = "Environmental systems, resource planning, and sustainability practice.", CourseStartDateSnapshot = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 145m, MiscFeeAmountSnapshot = 17m, GstAmountSnapshot = 18m, TaxRateSnapshot = 0.09m, GrossAmount = 180m, SubsidyAmount = 0m, NetAmount = 180m, PaidAmount = 180m, RemainingAmount = 0m, CreatedAt = createdAt },
                new Charge { Id = 5, EnrollmentId = 5, Status = ChargeStatus.Unpaid, SchoolNameSnapshot = "Central Heights School", CourseCodeSnapshot = "CRS-2026-E5F6G7H", CourseNameSnapshot = "Digital Media Production", CourseDescriptionSnapshot = "Digital storytelling, layout, and media production workflows.", CourseStartDateSnapshot = new DateTime(2026, 7, 15, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 9, 15, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 160m, MiscFeeAmountSnapshot = 20m, GstAmountSnapshot = 20m, TaxRateSnapshot = 0.09m, GrossAmount = 200m, SubsidyAmount = 0m, NetAmount = 200m, PaidAmount = 180m, RemainingAmount = 20m, CreatedAt = createdAt },
                new Charge { Id = 6, EnrollmentId = 6, Status = ChargeStatus.Overdue, SchoolNameSnapshot = "Riverside Learning Institute", CourseCodeSnapshot = "CRS-2026-F6G7H8J", CourseNameSnapshot = "Service Operations Practicum", CourseDescriptionSnapshot = "Customer operations, service standards, and scenario-based practice.", CourseStartDateSnapshot = new DateTime(2026, 7, 16, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 9, 16, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 175m, MiscFeeAmountSnapshot = 22m, GstAmountSnapshot = 23m, TaxRateSnapshot = 0.09m, GrossAmount = 220m, SubsidyAmount = 0m, NetAmount = 220m, PaidAmount = 150m, RemainingAmount = 70m, BecameOutstandingAt = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), LastAutoDeductedAt = new DateTime(2026, 3, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Charge { Id = 7, EnrollmentId = 7, Status = ChargeStatus.Unpaid, SchoolNameSnapshot = "Lakeside Technical School", CourseCodeSnapshot = "CRS-2026-G7H8J9K", CourseNameSnapshot = "Electrical Systems Fundamentals", CourseDescriptionSnapshot = "Foundational electrical theory, components, and safety practices.", CourseStartDateSnapshot = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 190m, MiscFeeAmountSnapshot = 25m, GstAmountSnapshot = 25m, TaxRateSnapshot = 0.09m, GrossAmount = 240m, SubsidyAmount = 0m, NetAmount = 240m, PaidAmount = 200m, RemainingAmount = 40m, CreatedAt = createdAt },
                new Charge { Id = 8, EnrollmentId = 8, Status = ChargeStatus.Overdue, SchoolNameSnapshot = "Greenfield Academy", CourseCodeSnapshot = "CRS-2026-H8J9K0L", CourseNameSnapshot = "Creative Writing Studio", CourseDescriptionSnapshot = "Narrative craft, editing practice, and guided writing critique.", CourseStartDateSnapshot = new DateTime(2026, 5, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 205m, MiscFeeAmountSnapshot = 27m, GstAmountSnapshot = 28m, TaxRateSnapshot = 0.09m, GrossAmount = 260m, SubsidyAmount = 0m, NetAmount = 260m, PaidAmount = 200m, RemainingAmount = 60m, BecameOutstandingAt = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), LastAutoDeductedAt = new DateTime(2026, 4, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Charge { Id = 9, EnrollmentId = 9, Status = ChargeStatus.Overdue, SchoolNameSnapshot = "Harbourfront School", CourseCodeSnapshot = "CRS-2026-J9K0L1M", CourseNameSnapshot = "Data Analytics Essentials", CourseDescriptionSnapshot = "Data preparation, analysis, visualization, and reporting fundamentals.", CourseStartDateSnapshot = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 5, 8, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 220m, MiscFeeAmountSnapshot = 30m, GstAmountSnapshot = 30m, TaxRateSnapshot = 0.09m, GrossAmount = 280m, SubsidyAmount = 0m, NetAmount = 280m, PaidAmount = 0m, RemainingAmount = 280m, BecameOutstandingAt = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Charge { Id = 10, EnrollmentId = 10, Status = ChargeStatus.Overdue, SchoolNameSnapshot = "Hillcrest Education Centre", CourseCodeSnapshot = "CRS-2026-K0L1M2N", CourseNameSnapshot = "Office Productivity for Business", CourseDescriptionSnapshot = "Document, spreadsheet, and presentation workflows for business users.", CourseStartDateSnapshot = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 5, 9, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 235m, MiscFeeAmountSnapshot = 32m, GstAmountSnapshot = 33m, TaxRateSnapshot = 0.09m, GrossAmount = 300m, SubsidyAmount = 0m, NetAmount = 300m, PaidAmount = 0m, RemainingAmount = 300m, BecameOutstandingAt = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

            return modelBuilder;
        }
    }
}

