using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding;

public sealed class ChargeSeedBuilder : ISeedBuilder
{
    public int Priority => 130;

    public ModelBuilder Seed(ModelBuilder modelBuilder)
    {
        var createdAt = SeedDataConstants.CreatedAt;

        modelBuilder.Entity<Charge>().HasData(
            new Charge { Id = 1, EnrollmentId = 1, Status = ChargeStatus.Paid, SchoolNameSnapshot = "Northview Secondary School", CourseCodeSnapshot = "CRS-2026-A1B2C3D", CourseNameSnapshot = "Applied Mathematics", CourseDescriptionSnapshot = "Foundation course in applied mathematics.", CourseStartDateSnapshot = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 12, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 100m, MiscFeeAmountSnapshot = 10m, GstAmountSnapshot = 10m, GrossAmount = 120m, SubsidyAmount = 0m, NetAmount = 120m, PaidAmount = 120m, RemainingAmount = 0m, CreatedAt = createdAt },
            new Charge { Id = 2, EnrollmentId = 2, Status = ChargeStatus.PartiallyPaid, SchoolNameSnapshot = "Eastbridge Secondary School", CourseCodeSnapshot = "CRS-2026-B2C3D4E", CourseNameSnapshot = "Computer Science Fundamentals", CourseDescriptionSnapshot = "Introduction to programming and computing.", CourseStartDateSnapshot = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 12, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 115m, MiscFeeAmountSnapshot = 12m, GstAmountSnapshot = 13m, GrossAmount = 140m, SubsidyAmount = 0m, NetAmount = 140m, PaidAmount = 70m, RemainingAmount = 70m, CreatedAt = createdAt },
            new Charge { Id = 3, EnrollmentId = 3, Status = ChargeStatus.PartiallyPaid, SchoolNameSnapshot = "Westhaven Secondary School", CourseCodeSnapshot = "CRS-2026-C3D4E5F", CourseNameSnapshot = "Business Communication", CourseDescriptionSnapshot = "Professional written and verbal communication.", CourseStartDateSnapshot = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 130m, MiscFeeAmountSnapshot = 15m, GstAmountSnapshot = 15m, GrossAmount = 160m, SubsidyAmount = 0m, NetAmount = 160m, PaidAmount = 140m, RemainingAmount = 20m, CreatedAt = createdAt },
            new Charge { Id = 4, EnrollmentId = 4, Status = ChargeStatus.Paid, SchoolNameSnapshot = "Southpoint Secondary School", CourseCodeSnapshot = "CRS-2026-D4E5F6G", CourseNameSnapshot = "Environmental Science", CourseDescriptionSnapshot = "Environmental systems and sustainability.", CourseStartDateSnapshot = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 145m, MiscFeeAmountSnapshot = 17m, GstAmountSnapshot = 18m, GrossAmount = 180m, SubsidyAmount = 0m, NetAmount = 180m, PaidAmount = 180m, RemainingAmount = 0m, CreatedAt = createdAt },
            new Charge { Id = 5, EnrollmentId = 5, Status = ChargeStatus.PartiallyPaid, SchoolNameSnapshot = "Central Heights School", CourseCodeSnapshot = "CRS-2026-E5F6G7H", CourseNameSnapshot = "Digital Media Design", CourseDescriptionSnapshot = "Digital design principles and production.", CourseStartDateSnapshot = new DateTime(2026, 7, 15, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 9, 15, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 160m, MiscFeeAmountSnapshot = 20m, GstAmountSnapshot = 20m, GrossAmount = 200m, SubsidyAmount = 0m, NetAmount = 200m, PaidAmount = 180m, RemainingAmount = 20m, CreatedAt = createdAt },
            new Charge { Id = 6, EnrollmentId = 6, Status = ChargeStatus.Outstanding, SchoolNameSnapshot = "Riverside Learning Institute", CourseCodeSnapshot = "CRS-2026-F6G7H8J", CourseNameSnapshot = "Hospitality Operations", CourseDescriptionSnapshot = "Core hospitality service operations.", CourseStartDateSnapshot = new DateTime(2026, 7, 16, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 9, 16, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 175m, MiscFeeAmountSnapshot = 22m, GstAmountSnapshot = 23m, GrossAmount = 220m, SubsidyAmount = 0m, NetAmount = 220m, PaidAmount = 150m, RemainingAmount = 70m, BecameOutstandingAt = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), LastAutoDeductedAt = new DateTime(2026, 3, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Charge { Id = 7, EnrollmentId = 7, Status = ChargeStatus.PartiallyPaid, SchoolNameSnapshot = "Lakeside Technical School", CourseCodeSnapshot = "CRS-2026-G7H8J9K", CourseNameSnapshot = "Electrical Engineering Basics", CourseDescriptionSnapshot = "Fundamentals of electrical systems.", CourseStartDateSnapshot = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 190m, MiscFeeAmountSnapshot = 25m, GstAmountSnapshot = 25m, GrossAmount = 240m, SubsidyAmount = 0m, NetAmount = 240m, PaidAmount = 200m, RemainingAmount = 40m, CreatedAt = createdAt },
            new Charge { Id = 8, EnrollmentId = 8, Status = ChargeStatus.Outstanding, SchoolNameSnapshot = "Greenfield Academy", CourseCodeSnapshot = "CRS-2026-H8J9K0L", CourseNameSnapshot = "Creative Writing", CourseDescriptionSnapshot = "Writing techniques across common genres.", CourseStartDateSnapshot = new DateTime(2026, 5, 2, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 205m, MiscFeeAmountSnapshot = 27m, GstAmountSnapshot = 28m, GrossAmount = 260m, SubsidyAmount = 0m, NetAmount = 260m, PaidAmount = 200m, RemainingAmount = 60m, BecameOutstandingAt = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), LastAutoDeductedAt = new DateTime(2026, 4, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Charge { Id = 9, EnrollmentId = 9, Status = ChargeStatus.Outstanding, SchoolNameSnapshot = "Harbourfront School", CourseCodeSnapshot = "CRS-2026-J9K0L1M", CourseNameSnapshot = "Data Analytics", CourseDescriptionSnapshot = "Data preparation, analysis and reporting.", CourseStartDateSnapshot = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 5, 8, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 220m, MiscFeeAmountSnapshot = 30m, GstAmountSnapshot = 30m, GrossAmount = 280m, SubsidyAmount = 0m, NetAmount = 280m, PaidAmount = 0m, RemainingAmount = 280m, BecameOutstandingAt = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Charge { Id = 10, EnrollmentId = 10, Status = ChargeStatus.Outstanding, SchoolNameSnapshot = "Hillcrest Education Centre", CourseCodeSnapshot = "CRS-2026-K0L1M2N", CourseNameSnapshot = "Legacy Office Applications", CourseDescriptionSnapshot = "Archived office applications programme.", CourseStartDateSnapshot = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), CourseEndDateSnapshot = new DateTime(2026, 5, 9, 0, 0, 0, DateTimeKind.Utc), CourseFeeAmountSnapshot = 235m, MiscFeeAmountSnapshot = 32m, GstAmountSnapshot = 33m, GrossAmount = 300m, SubsidyAmount = 0m, NetAmount = 300m, PaidAmount = 0m, RemainingAmount = 300m, BecameOutstandingAt = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

        return modelBuilder;
    }
}