using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class CourseSeedBuilder : ISeedBuilder
    {
        public int Priority => 80;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<Course>().HasData(
                new Course { Id = 1, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 1), CourseName = "Academic Writing Cohort 01", CourseFeeAmount = 125m, MiscFeeAmount = 23m, GstAmount = 13.32m, EnrollmentDeadline = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 2, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 2), CourseName = "Business Numeracy Cohort 02", CourseFeeAmount = 130m, MiscFeeAmount = 26m, GstAmount = 14.04m, EnrollmentDeadline = new DateTime(2026, 2, 2, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 2, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 3, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 3), CourseName = "Digital Literacy Cohort 03", CourseFeeAmount = 135m, MiscFeeAmount = 29m, GstAmount = 14.76m, EnrollmentDeadline = new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 3, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 4, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 4), CourseName = "Career Readiness Cohort 04", CourseFeeAmount = 140m, MiscFeeAmount = 32m, GstAmount = 15.48m, EnrollmentDeadline = new DateTime(2026, 2, 4, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 4, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 4, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 4, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 5, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 5), CourseName = "Applied Science Cohort 05", CourseFeeAmount = 145m, MiscFeeAmount = 20m, GstAmount = 14.85m, EnrollmentDeadline = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 5, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 6, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 6), CourseName = "Financial Literacy Cohort 06", CourseFeeAmount = 150m, MiscFeeAmount = 23m, GstAmount = 15.57m, EnrollmentDeadline = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 6, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 6, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 7, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 7), CourseName = "Project Collaboration Cohort 07", CourseFeeAmount = 155m, MiscFeeAmount = 26m, GstAmount = 16.29m, EnrollmentDeadline = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 7, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 7, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 8, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 8), CourseName = "Data Skills Cohort 08", CourseFeeAmount = 160m, MiscFeeAmount = 29m, GstAmount = 17.01m, EnrollmentDeadline = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 8, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 8, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 9, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 9), CourseName = "Workplace Communication Cohort 09", CourseFeeAmount = 165m, MiscFeeAmount = 32m, GstAmount = 17.73m, EnrollmentDeadline = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 9, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 9, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 10, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 10), CourseName = "Software Foundations Cohort 10", CourseFeeAmount = 170m, MiscFeeAmount = 20m, GstAmount = 17.10m, EnrollmentDeadline = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 10, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 11, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 11), CourseName = "Academic Writing Cohort 11", CourseFeeAmount = 175m, MiscFeeAmount = 23m, GstAmount = 17.82m, EnrollmentDeadline = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 11, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 11, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 12, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 12), CourseName = "Business Numeracy Cohort 12", CourseFeeAmount = 180m, MiscFeeAmount = 26m, GstAmount = 18.54m, EnrollmentDeadline = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 12, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 12, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 13, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 13), CourseName = "Digital Literacy Cohort 13", CourseFeeAmount = 185m, MiscFeeAmount = 29m, GstAmount = 19.26m, EnrollmentDeadline = new DateTime(2026, 2, 13, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 13, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 13, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 13, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 14, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 14), CourseName = "Career Readiness Cohort 14", CourseFeeAmount = 190m, MiscFeeAmount = 32m, GstAmount = 19.98m, EnrollmentDeadline = new DateTime(2026, 2, 14, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 14, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 14, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 14, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 15, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 15), CourseName = "Applied Science Cohort 15", CourseFeeAmount = 195m, MiscFeeAmount = 20m, GstAmount = 19.35m, EnrollmentDeadline = new DateTime(2026, 2, 15, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 15, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 15, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 16, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 16), CourseName = "Financial Literacy Cohort 16", CourseFeeAmount = 200m, MiscFeeAmount = 23m, GstAmount = 20.07m, EnrollmentDeadline = new DateTime(2026, 2, 16, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 16, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 16, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 16, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 17, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 17), CourseName = "Project Collaboration Cohort 17", CourseFeeAmount = 205m, MiscFeeAmount = 26m, GstAmount = 20.79m, EnrollmentDeadline = new DateTime(2026, 2, 17, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 17, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 17, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 17, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 18, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 18), CourseName = "Data Skills Cohort 18", CourseFeeAmount = 210m, MiscFeeAmount = 29m, GstAmount = 21.51m, EnrollmentDeadline = new DateTime(2026, 2, 18, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 18, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 18, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 18, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 19, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 19), CourseName = "Workplace Communication Cohort 19", CourseFeeAmount = 215m, MiscFeeAmount = 32m, GstAmount = 22.23m, EnrollmentDeadline = new DateTime(2026, 2, 19, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 19, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 19, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 19, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 20, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 20), CourseName = "Software Foundations Cohort 20", CourseFeeAmount = 220m, MiscFeeAmount = 20m, GstAmount = 21.60m, EnrollmentDeadline = new DateTime(2026, 2, 20, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 20, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 20, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 20, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 21, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 21), CourseName = "Academic Writing Cohort 21", CourseFeeAmount = 225m, MiscFeeAmount = 23m, GstAmount = 22.32m, EnrollmentDeadline = new DateTime(2026, 2, 21, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 21, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 21, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 21, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 22, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 22), CourseName = "Business Numeracy Cohort 22", CourseFeeAmount = 230m, MiscFeeAmount = 26m, GstAmount = 23.04m, EnrollmentDeadline = new DateTime(2026, 2, 22, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 22, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 22, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 22, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 23, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 23), CourseName = "Digital Literacy Cohort 23", CourseFeeAmount = 235m, MiscFeeAmount = 29m, GstAmount = 23.76m, EnrollmentDeadline = new DateTime(2026, 2, 23, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 23, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 23, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 23, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 24, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 24), CourseName = "Career Readiness Cohort 24", CourseFeeAmount = 240m, MiscFeeAmount = 32m, GstAmount = 24.48m, EnrollmentDeadline = new DateTime(2026, 2, 24, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 24, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 24, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 24, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 25, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 25), CourseName = "Applied Science Cohort 25", CourseFeeAmount = 245m, MiscFeeAmount = 20m, GstAmount = 23.85m, EnrollmentDeadline = new DateTime(2026, 2, 25, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 25, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 25, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 25, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 26, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 26), CourseName = "Financial Literacy Cohort 26", CourseFeeAmount = 250m, MiscFeeAmount = 23m, GstAmount = 24.57m, EnrollmentDeadline = new DateTime(2026, 2, 26, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 26, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 26, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 26, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 27, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 27), CourseName = "Project Collaboration Cohort 27", CourseFeeAmount = 255m, MiscFeeAmount = 26m, GstAmount = 25.29m, EnrollmentDeadline = new DateTime(2026, 2, 27, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 27, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 27, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 27, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 28, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 28), CourseName = "Data Skills Cohort 28", CourseFeeAmount = 260m, MiscFeeAmount = 29m, GstAmount = 26.01m, EnrollmentDeadline = new DateTime(2026, 2, 28, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 28, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 28, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 28, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 29, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 29), CourseName = "Workplace Communication Cohort 29", CourseFeeAmount = 265m, MiscFeeAmount = 32m, GstAmount = 26.73m, EnrollmentDeadline = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 30, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 30), CourseName = "Software Foundations Cohort 30", CourseFeeAmount = 270m, MiscFeeAmount = 20m, GstAmount = 26.10m, EnrollmentDeadline = new DateTime(2026, 2, 2, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 2, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 2, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 2, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 31, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 31), CourseName = "Academic Writing Cohort 31", CourseFeeAmount = 275m, MiscFeeAmount = 23m, GstAmount = 26.82m, EnrollmentDeadline = new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 3, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 32, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 32), CourseName = "Business Numeracy Cohort 32", CourseFeeAmount = 280m, MiscFeeAmount = 26m, GstAmount = 27.54m, EnrollmentDeadline = new DateTime(2026, 2, 4, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 4, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 4, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 4, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 33, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 33), CourseName = "Digital Literacy Cohort 33", CourseFeeAmount = 285m, MiscFeeAmount = 29m, GstAmount = 28.26m, EnrollmentDeadline = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 5, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 34, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 34), CourseName = "Career Readiness Cohort 34", CourseFeeAmount = 290m, MiscFeeAmount = 32m, GstAmount = 28.98m, EnrollmentDeadline = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 6, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 6, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 35, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 35), CourseName = "Applied Science Cohort 35", CourseFeeAmount = 295m, MiscFeeAmount = 20m, GstAmount = 28.35m, EnrollmentDeadline = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 7, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 7, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 36, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 36), CourseName = "Financial Literacy Cohort 36", CourseFeeAmount = 300m, MiscFeeAmount = 23m, GstAmount = 29.07m, EnrollmentDeadline = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 8, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 8, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 37, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 37), CourseName = "Project Collaboration Cohort 37", CourseFeeAmount = 305m, MiscFeeAmount = 26m, GstAmount = 29.79m, EnrollmentDeadline = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 9, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 9, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 38, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 38), CourseName = "Data Skills Cohort 38", CourseFeeAmount = 310m, MiscFeeAmount = 29m, GstAmount = 30.51m, EnrollmentDeadline = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 10, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 39, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 39), CourseName = "Workplace Communication Cohort 39", CourseFeeAmount = 315m, MiscFeeAmount = 32m, GstAmount = 31.23m, EnrollmentDeadline = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 11, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 11, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 11, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 40, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 40), CourseName = "Software Foundations Cohort 40", CourseFeeAmount = 320m, MiscFeeAmount = 20m, GstAmount = 30.60m, EnrollmentDeadline = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 12, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 12, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 41, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 41), CourseName = "Academic Writing Cohort 41", CourseFeeAmount = 325m, MiscFeeAmount = 23m, GstAmount = 31.32m, EnrollmentDeadline = new DateTime(2026, 2, 13, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 13, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 13, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 13, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 42, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 42), CourseName = "Business Numeracy Cohort 42", CourseFeeAmount = 330m, MiscFeeAmount = 26m, GstAmount = 32.04m, EnrollmentDeadline = new DateTime(2026, 2, 14, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 14, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 14, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 14, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 43, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 43), CourseName = "Digital Literacy Cohort 43", CourseFeeAmount = 335m, MiscFeeAmount = 29m, GstAmount = 32.76m, EnrollmentDeadline = new DateTime(2026, 2, 15, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 15, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 15, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 15, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 44, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 44), CourseName = "Career Readiness Cohort 44", CourseFeeAmount = 340m, MiscFeeAmount = 32m, GstAmount = 33.48m, EnrollmentDeadline = new DateTime(2026, 2, 16, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 16, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 16, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 16, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 45, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 45), CourseName = "Applied Science Cohort 45", CourseFeeAmount = 345m, MiscFeeAmount = 20m, GstAmount = 32.85m, EnrollmentDeadline = new DateTime(2026, 2, 17, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 17, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 17, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 17, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 46, SchoolId = 1, Status = CourseStatus.Draft, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 46), CourseName = "Financial Literacy Cohort 46", CourseFeeAmount = 350m, MiscFeeAmount = 23m, GstAmount = 33.57m, EnrollmentDeadline = new DateTime(2026, 2, 18, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 18, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 18, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 18, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 47, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 47), CourseName = "Project Collaboration Cohort 47", CourseFeeAmount = 355m, MiscFeeAmount = 26m, GstAmount = 34.29m, EnrollmentDeadline = new DateTime(2026, 2, 19, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 19, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 19, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 19, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 48, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 48), CourseName = "Data Skills Cohort 48", CourseFeeAmount = 360m, MiscFeeAmount = 29m, GstAmount = 35.01m, EnrollmentDeadline = new DateTime(2026, 2, 20, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 20, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 20, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 20, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 49, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 49), CourseName = "Workplace Communication Cohort 49", CourseFeeAmount = 365m, MiscFeeAmount = 32m, GstAmount = 35.73m, EnrollmentDeadline = new DateTime(2026, 2, 21, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 21, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 21, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 21, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 50, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 50), CourseName = "Software Foundations Cohort 50", CourseFeeAmount = 370m, MiscFeeAmount = 20m, GstAmount = 35.10m, EnrollmentDeadline = new DateTime(2026, 2, 22, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 22, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 22, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 22, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                // Sterling Quach additional courses for full installment status coverage
                new Course { Id = 51, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 51), CourseName = "Creative Thinking Cohort 51", CourseFeeAmount = 150m, MiscFeeAmount = 20m, GstAmount = 15.30m, EnrollmentDeadline = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 52, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 52), CourseName = "Critical Analysis Cohort 52", CourseFeeAmount = 160m, MiscFeeAmount = 25m, GstAmount = 16.65m, EnrollmentDeadline = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 4, 5, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 53, SchoolId = 1, Status = CourseStatus.Enrolling, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 53), CourseName = "Public Speaking Cohort 53", CourseFeeAmount = 140m, MiscFeeAmount = 18m, GstAmount = 14.22m, EnrollmentDeadline = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 54, SchoolId = 1, Status = CourseStatus.Closed, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 54), CourseName = "Data Literacy Cohort 54", CourseFeeAmount = 170m, MiscFeeAmount = 22m, GstAmount = 17.28m, EnrollmentDeadline = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 4, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new Course { Id = 55, SchoolId = 1, Status = CourseStatus.InProgress, CourseCode = SeedBusinessCodeUtil.Generate(BusinessCodeGenerator.CoursePrefix, 55), CourseName = "Problem Solving Cohort 55", CourseFeeAmount = 155m, MiscFeeAmount = 20m, GstAmount = 15.75m, EnrollmentDeadline = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 15, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 15, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

            return modelBuilder;
        }
    }
}
