using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding;

public sealed class CourseSeedBuilder : ISeedBuilder
{
    public int Priority => 100;

    public ModelBuilder Seed(ModelBuilder modelBuilder)
    {
        var createdAt = SeedDataConstants.CreatedAt;

        modelBuilder.Entity<Course>().HasData(
            new Course { Id = 1, SchoolId = 1, Status = CourseStatus.Upcoming, CourseCode = "CRS-2026-A1B2C3D", CourseName = "Applied Mathematics", Description = "Foundation course in applied mathematics.", CourseFeeAmount = 100m, MiscFeeAmount = 10m, GstAmount = 9.90m, EnrollmentDueDate = new DateTime(2026, 1, 15, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 9, 30, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 2, SchoolId = 2, Status = CourseStatus.Upcoming, CourseCode = "CRS-2026-B2C3D4E", CourseName = "Computer Science Fundamentals", Description = "Introduction to programming and computing.", CourseFeeAmount = 115m, MiscFeeAmount = 12m, GstAmount = 11.43m, EnrollmentDueDate = new DateTime(2026, 1, 16, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 7, 2, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 2, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 3, SchoolId = 3, Status = CourseStatus.Upcoming, CourseCode = "CRS-2026-C3D4E5F", CourseName = "Business Communication", Description = "Professional written and verbal communication.", CourseFeeAmount = 130m, MiscFeeAmount = 15m, GstAmount = 13.05m, EnrollmentDueDate = new DateTime(2026, 1, 17, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 7, 3, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 8, 3, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 10, 2, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 4, SchoolId = 4, Status = CourseStatus.InProgress, CourseCode = "CRS-2026-D4E5F6G", CourseName = "Environmental Science", Description = "Environmental systems and sustainability.", CourseFeeAmount = 145m, MiscFeeAmount = 17m, GstAmount = 14.58m, EnrollmentDueDate = new DateTime(2026, 1, 4, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 4, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 4, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 8, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 5, SchoolId = 5, Status = CourseStatus.InProgress, CourseCode = "CRS-2026-E5F6G7H", CourseName = "Digital Media Design", Description = "Digital design principles and production.", CourseFeeAmount = 160m, MiscFeeAmount = 20m, GstAmount = 16.20m, EnrollmentDueDate = new DateTime(2026, 1, 5, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 5, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 8, 4, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 6, SchoolId = 6, Status = CourseStatus.InProgress, CourseCode = "CRS-2026-F6G7H8J", CourseName = "Hospitality Operations", Description = "Core hospitality service operations.", CourseFeeAmount = 175m, MiscFeeAmount = 22m, GstAmount = 17.73m, EnrollmentDueDate = new DateTime(2026, 1, 6, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 5, 6, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 8, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 7, SchoolId = 7, Status = CourseStatus.Closed, CourseCode = "CRS-2026-G7H8J9K", CourseName = "Electrical Engineering Basics", Description = "Fundamentals of electrical systems.", CourseFeeAmount = 190m, MiscFeeAmount = 25m, GstAmount = 19.35m, EnrollmentDueDate = new DateTime(2026, 1, 7, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 7, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 6, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 8, SchoolId = 8, Status = CourseStatus.Closed, CourseCode = "CRS-2026-H8J9K0L", CourseName = "Creative Writing", Description = "Writing techniques across common genres.", CourseFeeAmount = 205m, MiscFeeAmount = 27m, GstAmount = 20.88m, EnrollmentDueDate = new DateTime(2026, 1, 8, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 8, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 7, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 9, SchoolId = 9, Status = CourseStatus.Closed, CourseCode = "CRS-2026-J9K0L1M", CourseName = "Data Analytics", Description = "Data preparation, analysis and reporting.", CourseFeeAmount = 220m, MiscFeeAmount = 30m, GstAmount = 22.50m, EnrollmentDueDate = new DateTime(2026, 1, 9, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 9, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 8, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
            new Course { Id = 10, SchoolId = 10, Status = CourseStatus.Closed, CourseCode = "CRS-2026-K0L1M2N", CourseName = "Legacy Office Applications", Description = "Archived office applications programme.", CourseFeeAmount = 235m, MiscFeeAmount = 32m, GstAmount = 24.03m, EnrollmentDueDate = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), FasApplicationDueDate = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc), StartDate = new DateTime(2026, 3, 10, 0, 0, 0, DateTimeKind.Utc), EndDate = new DateTime(2026, 5, 9, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

        return modelBuilder;
    }
}
