using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class EducationCreditTransactionSeedBuilder : ISeedBuilder
    {
        public int Priority => 130;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<EducationCreditTransaction>().HasData(
                new EducationCreditTransaction { Id = 1, TransactionCode = new Guid("49594d61-4376-40b8-ac80-939fdcc75d03"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 60m, BalanceBefore = 1020m, BalanceAfter = 1080m, Description = "Initial top-up credit", EducationAccountId = 1, CreatedAt = createdAt.AddDays(0) },
                new EducationCreditTransaction { Id = 2, TransactionCode = new Guid("e0318f15-fdda-4abf-9c6b-419497da2df5"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 70m, BalanceBefore = 1040m, BalanceAfter = 970m, Description = "Monthly allowance credit", EducationAccountId = 2, CreatedAt = createdAt.AddDays(1) },
                new EducationCreditTransaction { Id = 3, TransactionCode = new Guid("3cc72b88-c9fe-4854-9f18-20216358e732"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 80m, BalanceBefore = 1060m, BalanceAfter = 980m, Description = "Transport support credit", EducationAccountId = 3, CreatedAt = createdAt.AddDays(2) },
                new EducationCreditTransaction { Id = 4, TransactionCode = new Guid("20a47861-e67b-4d7d-a411-fa77f197d86b"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 90m, BalanceBefore = 1080m, BalanceAfter = 990m, Description = "Payment allocation debit", EducationAccountId = 4, CreatedAt = createdAt.AddDays(3) },
                new EducationCreditTransaction { Id = 5, TransactionCode = new Guid("13a7d8f6-33b2-457f-83c9-013639995db0"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 100m, BalanceBefore = 1100m, BalanceAfter = 1200m, Description = "Course fee payment debit", EducationAccountId = 5, CreatedAt = createdAt.AddDays(4) },
                new EducationCreditTransaction { Id = 6, TransactionCode = new Guid("b173acbb-c707-4e20-8d42-f73c61af31eb"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 110m, BalanceBefore = 1120m, BalanceAfter = 1010m, Description = "Manual adjustment credit", EducationAccountId = 6, CreatedAt = createdAt.AddDays(5) },
                new EducationCreditTransaction { Id = 7, TransactionCode = new Guid("b9b22a3a-e1ed-445e-830d-3f7900433702"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 120m, BalanceBefore = 1140m, BalanceAfter = 1020m, Description = "Scheduled meal allowance", EducationAccountId = 7, CreatedAt = createdAt.AddDays(6) },
                new EducationCreditTransaction { Id = 8, TransactionCode = new Guid("9c034e05-2ad7-48f6-9d0e-1d75f3a9dc11"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 130m, BalanceBefore = 1160m, BalanceAfter = 1030m, Description = "Learning materials credit", EducationAccountId = 8, CreatedAt = createdAt.AddDays(7) },
                new EducationCreditTransaction { Id = 9, TransactionCode = new Guid("11b9710a-dc40-4940-8346-3426a0b08cc1"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 140m, BalanceBefore = 1180m, BalanceAfter = 1320m, Description = "Account balance correction", EducationAccountId = 9, CreatedAt = createdAt.AddDays(8) },
                new EducationCreditTransaction { Id = 10, TransactionCode = new Guid("534f9ac0-3749-48bf-9830-9c3a494e0357"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 50m, BalanceBefore = 1200m, BalanceAfter = 1150m, Description = "Tuition payment debit", EducationAccountId = 10, CreatedAt = createdAt.AddDays(9) },
                new EducationCreditTransaction { Id = 11, TransactionCode = new Guid("5a7565fa-724d-4ed7-a659-c55f2b82b148"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 60m, BalanceBefore = 1220m, BalanceAfter = 1160m, Description = "Initial top-up credit", EducationAccountId = 11, CreatedAt = createdAt.AddDays(10) },
                new EducationCreditTransaction { Id = 12, TransactionCode = new Guid("dce18490-c9c0-47d1-8888-bbc96fbeaa8f"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 70m, BalanceBefore = 1240m, BalanceAfter = 1170m, Description = "Monthly allowance credit", EducationAccountId = 12, CreatedAt = createdAt.AddDays(11) },
                new EducationCreditTransaction { Id = 13, TransactionCode = new Guid("26410860-8d9c-4653-b8dc-737d522a260c"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 80m, BalanceBefore = 1260m, BalanceAfter = 1340m, Description = "Transport support credit", EducationAccountId = 13, CreatedAt = createdAt.AddDays(12) },
                new EducationCreditTransaction { Id = 14, TransactionCode = new Guid("56c40714-1195-4170-ab78-fde7334aac85"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 90m, BalanceBefore = 1280m, BalanceAfter = 1190m, Description = "Payment allocation debit", EducationAccountId = 14, CreatedAt = createdAt.AddDays(13) },
                new EducationCreditTransaction { Id = 15, TransactionCode = new Guid("60b17549-097b-4586-bcc9-b7adcdd28ab0"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 100m, BalanceBefore = 1300m, BalanceAfter = 1200m, Description = "Course fee payment debit", EducationAccountId = 15, CreatedAt = createdAt.AddDays(14) },
                new EducationCreditTransaction { Id = 16, TransactionCode = new Guid("411d1141-302f-4164-a767-0427a915ca08"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 110m, BalanceBefore = 1320m, BalanceAfter = 1210m, Description = "Manual adjustment credit", EducationAccountId = 16, CreatedAt = createdAt.AddDays(15) },
                new EducationCreditTransaction { Id = 17, TransactionCode = new Guid("0bc2a282-c6de-47b7-98b0-fdac93855e55"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 120m, BalanceBefore = 1340m, BalanceAfter = 1460m, Description = "Scheduled meal allowance", EducationAccountId = 17, CreatedAt = createdAt.AddDays(16) },
                new EducationCreditTransaction { Id = 18, TransactionCode = new Guid("3a8d08c2-da97-4c08-9195-9c6fd5486e4f"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 130m, BalanceBefore = 1360m, BalanceAfter = 1230m, Description = "Learning materials credit", EducationAccountId = 18, CreatedAt = createdAt.AddDays(17) },
                new EducationCreditTransaction { Id = 19, TransactionCode = new Guid("8f433ea5-cfc6-4449-9915-76fba85d7474"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 140m, BalanceBefore = 1380m, BalanceAfter = 1240m, Description = "Account balance correction", EducationAccountId = 19, CreatedAt = createdAt.AddDays(18) },
                new EducationCreditTransaction { Id = 20, TransactionCode = new Guid("5a3b8e16-fa7f-4ae2-b395-4dd8e27c3c25"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 50m, BalanceBefore = 1400m, BalanceAfter = 1350m, Description = "Tuition payment debit", EducationAccountId = 20, CreatedAt = createdAt.AddDays(19) },
                new EducationCreditTransaction { Id = 21, TransactionCode = new Guid("af161551-4185-4376-a70e-b0ad42e7d980"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 60m, BalanceBefore = 1420m, BalanceAfter = 1480m, Description = "Initial top-up credit", EducationAccountId = 21, CreatedAt = createdAt.AddDays(0) },
                new EducationCreditTransaction { Id = 22, TransactionCode = new Guid("206fc099-fd74-4264-b317-04c0426e1be8"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 70m, BalanceBefore = 1440m, BalanceAfter = 1370m, Description = "Monthly allowance credit", EducationAccountId = 22, CreatedAt = createdAt.AddDays(1) },
                new EducationCreditTransaction { Id = 23, TransactionCode = new Guid("56b65cbf-d647-4447-90df-1b52a3f11fb6"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 80m, BalanceBefore = 1460m, BalanceAfter = 1380m, Description = "Transport support credit", EducationAccountId = 23, CreatedAt = createdAt.AddDays(2) },
                new EducationCreditTransaction { Id = 24, TransactionCode = new Guid("7867f9b5-1d38-4781-b786-4daeb46ad46f"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 90m, BalanceBefore = 1480m, BalanceAfter = 1390m, Description = "Payment allocation debit", EducationAccountId = 24, CreatedAt = createdAt.AddDays(3) },
                new EducationCreditTransaction { Id = 25, TransactionCode = new Guid("641eb577-86a7-48aa-855c-66b19f1bb194"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 100m, BalanceBefore = 1500m, BalanceAfter = 1600m, Description = "Course fee payment debit", EducationAccountId = 25, CreatedAt = createdAt.AddDays(4) },
                new EducationCreditTransaction { Id = 26, TransactionCode = new Guid("16b8a137-6519-48ba-95f8-00561fc14186"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 110m, BalanceBefore = 1520m, BalanceAfter = 1410m, Description = "Manual adjustment credit", EducationAccountId = 26, CreatedAt = createdAt.AddDays(5) },
                new EducationCreditTransaction { Id = 27, TransactionCode = new Guid("302e2943-b197-498a-92a2-3b56ee17c5c8"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 120m, BalanceBefore = 1540m, BalanceAfter = 1420m, Description = "Scheduled meal allowance", EducationAccountId = 27, CreatedAt = createdAt.AddDays(6) },
                new EducationCreditTransaction { Id = 28, TransactionCode = new Guid("0a68c2bf-fa68-482d-97df-5c7e8fe02e12"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 130m, BalanceBefore = 1560m, BalanceAfter = 1430m, Description = "Learning materials credit", EducationAccountId = 28, CreatedAt = createdAt.AddDays(7) },
                new EducationCreditTransaction { Id = 29, TransactionCode = new Guid("03ed2f50-9240-41d8-8ed5-d4d029e1f377"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 140m, BalanceBefore = 1580m, BalanceAfter = 1720m, Description = "Account balance correction", EducationAccountId = 29, CreatedAt = createdAt.AddDays(8) },
                new EducationCreditTransaction { Id = 30, TransactionCode = new Guid("947ff9d0-5119-4ae2-91b8-3c2ed6763e0a"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 50m, BalanceBefore = 1600m, BalanceAfter = 1550m, Description = "Tuition payment debit", EducationAccountId = 30, CreatedAt = createdAt.AddDays(9) },
                new EducationCreditTransaction { Id = 31, TransactionCode = new Guid("41c77e92-62c7-4e1b-9228-2a440f58347b"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 60m, BalanceBefore = 1620m, BalanceAfter = 1560m, Description = "Initial top-up credit", EducationAccountId = 31, CreatedAt = createdAt.AddDays(10) },
                new EducationCreditTransaction { Id = 32, TransactionCode = new Guid("19e0145e-509e-495b-a780-2fbca86bb7f0"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 70m, BalanceBefore = 1640m, BalanceAfter = 1570m, Description = "Monthly allowance credit", EducationAccountId = 32, CreatedAt = createdAt.AddDays(11) },
                new EducationCreditTransaction { Id = 33, TransactionCode = new Guid("4818a12d-3778-476f-818f-93513e797f82"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 80m, BalanceBefore = 1660m, BalanceAfter = 1740m, Description = "Transport support credit", EducationAccountId = 33, CreatedAt = createdAt.AddDays(12) },
                new EducationCreditTransaction { Id = 34, TransactionCode = new Guid("b866b87d-d793-495b-ba11-a8e4adb05302"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 90m, BalanceBefore = 1680m, BalanceAfter = 1590m, Description = "Payment allocation debit", EducationAccountId = 34, CreatedAt = createdAt.AddDays(13) },
                new EducationCreditTransaction { Id = 35, TransactionCode = new Guid("84a02f3a-4080-4a44-bee4-4c6c57238abd"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 100m, BalanceBefore = 1700m, BalanceAfter = 1600m, Description = "Course fee payment debit", EducationAccountId = 35, CreatedAt = createdAt.AddDays(14) },
                new EducationCreditTransaction { Id = 36, TransactionCode = new Guid("ef705496-e433-4e7d-a27b-2f283fd15f2d"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 110m, BalanceBefore = 1720m, BalanceAfter = 1610m, Description = "Manual adjustment credit", EducationAccountId = 36, CreatedAt = createdAt.AddDays(15) },
                new EducationCreditTransaction { Id = 37, TransactionCode = new Guid("a3a314a6-1a3c-4939-af36-3d1b4edcb340"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 120m, BalanceBefore = 1740m, BalanceAfter = 1860m, Description = "Scheduled meal allowance", EducationAccountId = 37, CreatedAt = createdAt.AddDays(16) },
                new EducationCreditTransaction { Id = 38, TransactionCode = new Guid("f8033fe6-a6f8-4ee1-a7d6-d9d92638dd47"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 130m, BalanceBefore = 1760m, BalanceAfter = 1630m, Description = "Learning materials credit", EducationAccountId = 38, CreatedAt = createdAt.AddDays(17) },
                new EducationCreditTransaction { Id = 39, TransactionCode = new Guid("e83276cf-8a65-4d36-8f34-56b2aceed589"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 140m, BalanceBefore = 1780m, BalanceAfter = 1640m, Description = "Account balance correction", EducationAccountId = 39, CreatedAt = createdAt.AddDays(18) },
                new EducationCreditTransaction { Id = 40, TransactionCode = new Guid("66360922-c48e-4a2e-a027-a250c090621b"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 50m, BalanceBefore = 1800m, BalanceAfter = 1750m, Description = "Tuition payment debit", EducationAccountId = 40, CreatedAt = createdAt.AddDays(19) },
                new EducationCreditTransaction { Id = 41, TransactionCode = new Guid("b24cc55a-d9d6-4496-af44-3a66f7554f54"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 60m, BalanceBefore = 1820m, BalanceAfter = 1880m, Description = "Initial top-up credit", EducationAccountId = 41, CreatedAt = createdAt.AddDays(0) },
                new EducationCreditTransaction { Id = 42, TransactionCode = new Guid("1ff96513-da7e-42f4-a069-3a2ca5d8683e"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 70m, BalanceBefore = 1840m, BalanceAfter = 1770m, Description = "Monthly allowance credit", EducationAccountId = 42, CreatedAt = createdAt.AddDays(1) },
                new EducationCreditTransaction { Id = 43, TransactionCode = new Guid("d63ba3cb-e4e2-43c9-ac55-44c8471a39ca"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 80m, BalanceBefore = 1860m, BalanceAfter = 1780m, Description = "Transport support credit", EducationAccountId = 43, CreatedAt = createdAt.AddDays(2) },
                new EducationCreditTransaction { Id = 44, TransactionCode = new Guid("a4b0db24-dd9d-46ad-bd0e-06338a7f223d"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 90m, BalanceBefore = 1880m, BalanceAfter = 1790m, Description = "Payment allocation debit", EducationAccountId = 44, CreatedAt = createdAt.AddDays(3) },
                new EducationCreditTransaction { Id = 45, TransactionCode = new Guid("fc22cb9e-b54e-4be1-8da5-4f6bc19f5872"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 100m, BalanceBefore = 1900m, BalanceAfter = 2000m, Description = "Course fee payment debit", EducationAccountId = 45, CreatedAt = createdAt.AddDays(4) },
                new EducationCreditTransaction { Id = 46, TransactionCode = new Guid("b8281119-e152-4b4b-a305-12a6cdac0443"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 110m, BalanceBefore = 1920m, BalanceAfter = 1810m, Description = "Manual adjustment credit", EducationAccountId = 46, CreatedAt = createdAt.AddDays(5) },
                new EducationCreditTransaction { Id = 47, TransactionCode = new Guid("aa3b2e4c-4168-41e1-9e2d-e42027d45872"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 120m, BalanceBefore = 1940m, BalanceAfter = 1820m, Description = "Scheduled meal allowance", EducationAccountId = 47, CreatedAt = createdAt.AddDays(6) },
                new EducationCreditTransaction { Id = 48, TransactionCode = new Guid("f2568b2f-b965-4d82-8bb2-0d344af9df0c"), Type = EducationCreditTransactionType.ExpiredBalance, Direction = EducationCreditTransactionDirection.Debit, Amount = 130m, BalanceBefore = 1960m, BalanceAfter = 1830m, Description = "Learning materials credit", EducationAccountId = 48, CreatedAt = createdAt.AddDays(7) },
                new EducationCreditTransaction { Id = 49, TransactionCode = new Guid("20489516-1121-469e-8d21-e46a93a2fffc"), Type = EducationCreditTransactionType.Topup, Direction = EducationCreditTransactionDirection.Credit, Amount = 140m, BalanceBefore = 1980m, BalanceAfter = 2120m, Description = "Account balance correction", EducationAccountId = 49, CreatedAt = createdAt.AddDays(8) },
                new EducationCreditTransaction { Id = 50, TransactionCode = new Guid("ed9be019-597a-4217-9b0e-d0c47009c4ec"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 50m, BalanceBefore = 2000m, BalanceAfter = 1950m, Description = "Tuition payment debit", EducationAccountId = 50, CreatedAt = createdAt.AddDays(9) },
                // Sterling Quach additional transaction for the paid installment
                new EducationCreditTransaction { Id = 51, TransactionCode = new Guid("c2a4b6d8-e0f2-4a6c-8e0a-2c4b6d8e0f2a"), Type = EducationCreditTransactionType.CourseFeePayment, Direction = EducationCreditTransactionDirection.Debit, Amount = 185m, BalanceBefore = 1025m, BalanceAfter = 840m, Description = "Course fee payment for Creative Thinking Cohort 51", EducationAccountId = 1, CreatedAt = createdAt.AddDays(30) });

            return modelBuilder;
        }
    }
}
