using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class EducationAccountSeedBuilder : ISeedBuilder
    {
        public int Priority => 60;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<EducationAccount>().HasData(
                new EducationAccount { Id = 1, AccountNumber = SeedAccountNumberUtil.Generate(1), EducationCreditBalance = 1025m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 1, CreatedAt = createdAt },
                new EducationAccount { Id = 2, AccountNumber = SeedAccountNumberUtil.Generate(2), EducationCreditBalance = 1050m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 2, CreatedAt = createdAt },
                new EducationAccount { Id = 3, AccountNumber = SeedAccountNumberUtil.Generate(3), EducationCreditBalance = 1075m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 3, ClosedAt = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 4, AccountNumber = SeedAccountNumberUtil.Generate(4), EducationCreditBalance = 1100m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 4, CreatedAt = createdAt },
                new EducationAccount { Id = 5, AccountNumber = SeedAccountNumberUtil.Generate(5), EducationCreditBalance = 1125m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 5, CreatedAt = createdAt },
                new EducationAccount { Id = 6, AccountNumber = SeedAccountNumberUtil.Generate(6), EducationCreditBalance = 1150m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 6, ClosedAt = new DateTime(2026, 6, 6, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 7, AccountNumber = SeedAccountNumberUtil.Generate(7), EducationCreditBalance = 1175m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 7, CreatedAt = createdAt },
                new EducationAccount { Id = 8, AccountNumber = SeedAccountNumberUtil.Generate(8), EducationCreditBalance = 1200m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 8, CreatedAt = createdAt },
                new EducationAccount { Id = 9, AccountNumber = SeedAccountNumberUtil.Generate(9), EducationCreditBalance = 1225m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 9, ClosedAt = new DateTime(2026, 6, 9, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 10, AccountNumber = SeedAccountNumberUtil.Generate(10), EducationCreditBalance = 1250m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 10, CreatedAt = createdAt },
                new EducationAccount { Id = 11, AccountNumber = SeedAccountNumberUtil.Generate(11), EducationCreditBalance = 1275m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 11, CreatedAt = createdAt },
                new EducationAccount { Id = 12, AccountNumber = SeedAccountNumberUtil.Generate(12), EducationCreditBalance = 1300m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 12, ClosedAt = new DateTime(2026, 6, 12, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 13, AccountNumber = SeedAccountNumberUtil.Generate(13), EducationCreditBalance = 1325m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 13, CreatedAt = createdAt },
                new EducationAccount { Id = 14, AccountNumber = SeedAccountNumberUtil.Generate(14), EducationCreditBalance = 1350m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 14, CreatedAt = createdAt },
                new EducationAccount { Id = 15, AccountNumber = SeedAccountNumberUtil.Generate(15), EducationCreditBalance = 1375m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 15, ClosedAt = new DateTime(2026, 6, 15, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 16, AccountNumber = SeedAccountNumberUtil.Generate(16), EducationCreditBalance = 1400m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 16, CreatedAt = createdAt },
                new EducationAccount { Id = 17, AccountNumber = SeedAccountNumberUtil.Generate(17), EducationCreditBalance = 1425m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 17, CreatedAt = createdAt },
                new EducationAccount { Id = 18, AccountNumber = SeedAccountNumberUtil.Generate(18), EducationCreditBalance = 1450m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 18, ClosedAt = new DateTime(2026, 6, 18, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 19, AccountNumber = SeedAccountNumberUtil.Generate(19), EducationCreditBalance = 1475m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 19, CreatedAt = createdAt },
                new EducationAccount { Id = 20, AccountNumber = SeedAccountNumberUtil.Generate(20), EducationCreditBalance = 1500m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 20, CreatedAt = createdAt },
                new EducationAccount { Id = 21, AccountNumber = SeedAccountNumberUtil.Generate(21), EducationCreditBalance = 1525m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 21, ClosedAt = new DateTime(2026, 6, 21, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 22, AccountNumber = SeedAccountNumberUtil.Generate(22), EducationCreditBalance = 1550m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 22, CreatedAt = createdAt },
                new EducationAccount { Id = 23, AccountNumber = SeedAccountNumberUtil.Generate(23), EducationCreditBalance = 1575m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 23, CreatedAt = createdAt },
                new EducationAccount { Id = 24, AccountNumber = SeedAccountNumberUtil.Generate(24), EducationCreditBalance = 1600m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 24, ClosedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 25, AccountNumber = SeedAccountNumberUtil.Generate(25), EducationCreditBalance = 1625m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 25, CreatedAt = createdAt },
                new EducationAccount { Id = 26, AccountNumber = SeedAccountNumberUtil.Generate(26), EducationCreditBalance = 1650m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 26, CreatedAt = createdAt },
                new EducationAccount { Id = 27, AccountNumber = SeedAccountNumberUtil.Generate(27), EducationCreditBalance = 1675m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 27, ClosedAt = new DateTime(2026, 6, 27, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 28, AccountNumber = SeedAccountNumberUtil.Generate(28), EducationCreditBalance = 1700m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 28, CreatedAt = createdAt },
                new EducationAccount { Id = 29, AccountNumber = SeedAccountNumberUtil.Generate(29), EducationCreditBalance = 1725m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 29, CreatedAt = createdAt },
                new EducationAccount { Id = 30, AccountNumber = SeedAccountNumberUtil.Generate(30), EducationCreditBalance = 1750m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 30, ClosedAt = new DateTime(2026, 6, 2, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 31, AccountNumber = SeedAccountNumberUtil.Generate(31), EducationCreditBalance = 1775m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 31, CreatedAt = createdAt },
                new EducationAccount { Id = 32, AccountNumber = SeedAccountNumberUtil.Generate(32), EducationCreditBalance = 1800m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 32, CreatedAt = createdAt },
                new EducationAccount { Id = 33, AccountNumber = SeedAccountNumberUtil.Generate(33), EducationCreditBalance = 1825m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 33, ClosedAt = new DateTime(2026, 6, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 34, AccountNumber = SeedAccountNumberUtil.Generate(34), EducationCreditBalance = 1850m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 34, CreatedAt = createdAt },
                new EducationAccount { Id = 35, AccountNumber = SeedAccountNumberUtil.Generate(35), EducationCreditBalance = 1875m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 35, CreatedAt = createdAt },
                new EducationAccount { Id = 36, AccountNumber = SeedAccountNumberUtil.Generate(36), EducationCreditBalance = 1900m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 36, ClosedAt = new DateTime(2026, 6, 8, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 37, AccountNumber = SeedAccountNumberUtil.Generate(37), EducationCreditBalance = 1925m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 37, CreatedAt = createdAt },
                new EducationAccount { Id = 38, AccountNumber = SeedAccountNumberUtil.Generate(38), EducationCreditBalance = 1950m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 38, CreatedAt = createdAt },
                new EducationAccount { Id = 39, AccountNumber = SeedAccountNumberUtil.Generate(39), EducationCreditBalance = 1975m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 39, ClosedAt = new DateTime(2026, 6, 11, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 40, AccountNumber = SeedAccountNumberUtil.Generate(40), EducationCreditBalance = 2000m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 40, CreatedAt = createdAt },
                new EducationAccount { Id = 41, AccountNumber = SeedAccountNumberUtil.Generate(41), EducationCreditBalance = 2025m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 41, CreatedAt = createdAt },
                new EducationAccount { Id = 42, AccountNumber = SeedAccountNumberUtil.Generate(42), EducationCreditBalance = 2050m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 42, ClosedAt = new DateTime(2026, 6, 14, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 43, AccountNumber = SeedAccountNumberUtil.Generate(43), EducationCreditBalance = 2075m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 43, CreatedAt = createdAt },
                new EducationAccount { Id = 44, AccountNumber = SeedAccountNumberUtil.Generate(44), EducationCreditBalance = 2100m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 44, CreatedAt = createdAt },
                new EducationAccount { Id = 45, AccountNumber = SeedAccountNumberUtil.Generate(45), EducationCreditBalance = 2125m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 45, ClosedAt = new DateTime(2026, 6, 17, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 46, AccountNumber = SeedAccountNumberUtil.Generate(46), EducationCreditBalance = 2150m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 46, CreatedAt = createdAt },
                new EducationAccount { Id = 47, AccountNumber = SeedAccountNumberUtil.Generate(47), EducationCreditBalance = 2175m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 47, CreatedAt = createdAt },
                new EducationAccount { Id = 48, AccountNumber = SeedAccountNumberUtil.Generate(48), EducationCreditBalance = 2200m, Status = EducationAccountStatus.Closed, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 48, ClosedAt = new DateTime(2026, 6, 20, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new EducationAccount { Id = 49, AccountNumber = SeedAccountNumberUtil.Generate(49), EducationCreditBalance = 2225m, Status = EducationAccountStatus.Active, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 49, CreatedAt = createdAt },
                new EducationAccount { Id = 50, AccountNumber = SeedAccountNumberUtil.Generate(50), EducationCreditBalance = 2250m, Status = EducationAccountStatus.Extended, OpenedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CitizenId = 50, CreatedAt = createdAt });

            return modelBuilder;
        }
    }
}
