using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class EnrollmentSeedBuilder : ISeedBuilder
    {
        public int Priority => 120;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<Enrollment>().HasData(
                new Enrollment { Id = 1, CourseId = 1, SchoolStudentId = 1, SchoolNameSnapshot = "Northview Secondary School", CourseNameSnapshot = "Applied Mathematics", CourseDescriptionSnapshot = "Foundation course in applied mathematics.", CitizenNricSnapshot = SingaporeNricUtil.Generate(1), CitizenFullNameSnapshot = "Citizen 001", CitizenEmailSnapshot = "citizen001@example.com", CitizenPhoneNumberSnapshot = "+6590000001", AccountNumberSnapshot = "EDU-2026-00000000001", CreatedAt = createdAt },
                new Enrollment { Id = 2, CourseId = 2, SchoolStudentId = 2, SchoolNameSnapshot = "Eastbridge Secondary School", CourseNameSnapshot = "Computer Science Fundamentals", CourseDescriptionSnapshot = "Introduction to programming and computing.", CitizenNricSnapshot = SingaporeNricUtil.Generate(2), CitizenFullNameSnapshot = "Citizen 002", CitizenEmailSnapshot = "citizen002@example.com", CitizenPhoneNumberSnapshot = "+6590000002", AccountNumberSnapshot = "EDU-2026-00000000002", CreatedAt = createdAt },
                new Enrollment { Id = 3, CourseId = 3, SchoolStudentId = 3, SchoolNameSnapshot = "Westhaven Secondary School", CourseNameSnapshot = "Business Communication", CourseDescriptionSnapshot = "Professional written and verbal communication.", CitizenNricSnapshot = SingaporeNricUtil.Generate(3), CitizenFullNameSnapshot = "Citizen 003", CitizenEmailSnapshot = "citizen003@example.com", CitizenPhoneNumberSnapshot = "+6590000003", AccountNumberSnapshot = "EDU-2026-00000000003", CreatedAt = createdAt },
                new Enrollment { Id = 4, CourseId = 4, SchoolStudentId = 4, SchoolNameSnapshot = "Southpoint Secondary School", CourseNameSnapshot = "Environmental Science", CourseDescriptionSnapshot = "Environmental systems and sustainability.", CitizenNricSnapshot = SingaporeNricUtil.Generate(4), CitizenFullNameSnapshot = "Citizen 004", CitizenEmailSnapshot = "citizen004@example.com", CitizenPhoneNumberSnapshot = "+6590000004", AccountNumberSnapshot = "EDU-2026-00000000004", CreatedAt = createdAt },
                new Enrollment { Id = 5, CourseId = 5, SchoolStudentId = 5, SchoolNameSnapshot = "Central Heights School", CourseNameSnapshot = "Digital Media Design", CourseDescriptionSnapshot = "Digital design principles and production.", CitizenNricSnapshot = SingaporeNricUtil.Generate(5), CitizenFullNameSnapshot = "Citizen 005", CitizenEmailSnapshot = "citizen005@example.com", CitizenPhoneNumberSnapshot = "+6590000005", AccountNumberSnapshot = "EDU-2026-00000000005", CreatedAt = createdAt },
                new Enrollment { Id = 6, CourseId = 6, SchoolStudentId = 6, SchoolNameSnapshot = "Riverside Learning Institute", CourseNameSnapshot = "Hospitality Operations", CourseDescriptionSnapshot = "Core hospitality service operations.", CitizenNricSnapshot = SingaporeNricUtil.Generate(6), CitizenFullNameSnapshot = "Citizen 006", CitizenEmailSnapshot = "citizen006@example.com", CitizenPhoneNumberSnapshot = "+6590000006", AccountNumberSnapshot = "EDU-2026-00000000006", CreatedAt = createdAt },
                new Enrollment { Id = 7, CourseId = 7, SchoolStudentId = 7, SchoolNameSnapshot = "Lakeside Technical School", CourseNameSnapshot = "Electrical Engineering Basics", CourseDescriptionSnapshot = "Fundamentals of electrical systems.", CitizenNricSnapshot = SingaporeNricUtil.Generate(7), CitizenFullNameSnapshot = "Citizen 007", CitizenEmailSnapshot = "citizen007@example.com", CitizenPhoneNumberSnapshot = "+6590000007", AccountNumberSnapshot = "EDU-2026-00000000007", CreatedAt = createdAt },
                new Enrollment { Id = 8, CourseId = 8, SchoolStudentId = 8, SchoolNameSnapshot = "Greenfield Academy", CourseNameSnapshot = "Creative Writing", CourseDescriptionSnapshot = "Writing techniques across common genres.", CitizenNricSnapshot = SingaporeNricUtil.Generate(8), CitizenFullNameSnapshot = "Citizen 008", CitizenEmailSnapshot = "citizen008@example.com", CitizenPhoneNumberSnapshot = "+6590000008", AccountNumberSnapshot = "EDU-2026-00000000008", CreatedAt = createdAt },
                new Enrollment { Id = 9, CourseId = 9, SchoolStudentId = 9, SchoolNameSnapshot = "Harbourfront School", CourseNameSnapshot = "Data Analytics", CourseDescriptionSnapshot = "Data preparation, analysis and reporting.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 10, CourseId = 10, SchoolStudentId = 10, SchoolNameSnapshot = "Hillcrest Education Centre", CourseNameSnapshot = "Legacy Office Applications", CourseDescriptionSnapshot = "Archived office applications programme.", CitizenNricSnapshot = SingaporeNricUtil.Generate(10), CitizenFullNameSnapshot = "Citizen 010", CitizenEmailSnapshot = "citizen010@example.com", CitizenPhoneNumberSnapshot = "+6590000010", AccountNumberSnapshot = "EDU-2026-00000000010", CreatedAt = createdAt },
            
                // Upcoming courses (CourseId: 1, 2, 3)
                new Enrollment { Id = 11, CourseId = 1, SchoolStudentId = 9, SchoolNameSnapshot = "Northview Secondary School", CourseNameSnapshot = "Applied Mathematics", CourseDescriptionSnapshot = "Foundation course in applied mathematics.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 13, CourseId = 2, SchoolStudentId = 9, SchoolNameSnapshot = "Eastbridge Secondary School", CourseNameSnapshot = "Computer Science Fundamentals", CourseDescriptionSnapshot = "Introduction to programming and computing.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 14, CourseId = 3, SchoolStudentId = 9, SchoolNameSnapshot = "Westhaven Secondary School", CourseNameSnapshot = "Business Communication", CourseDescriptionSnapshot = "Professional written and verbal communication.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
            
                // InProgress courses (CourseId: 4, 5, 6)
                new Enrollment { Id = 12, CourseId = 4, SchoolStudentId = 9, SchoolNameSnapshot = "Southpoint Secondary School", CourseNameSnapshot = "Environmental Science", CourseDescriptionSnapshot = "Environmental systems and sustainability.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 15, CourseId = 5, SchoolStudentId = 9, SchoolNameSnapshot = "Central Heights School", CourseNameSnapshot = "Digital Media Design", CourseDescriptionSnapshot = "Digital design principles and production.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 16, CourseId = 6, SchoolStudentId = 9, SchoolNameSnapshot = "Riverside Learning Institute", CourseNameSnapshot = "Hospitality Operations", CourseDescriptionSnapshot = "Core hospitality service operations.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
            
                // Closed courses (CourseId: 7, 8, 9, 10) - 9 is already above, adding 7, 8, 10
                new Enrollment { Id = 17, CourseId = 7, SchoolStudentId = 9, SchoolNameSnapshot = "Lakeside Technical School", CourseNameSnapshot = "Electrical Engineering Basics", CourseDescriptionSnapshot = "Fundamentals of electrical systems.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 18, CourseId = 8, SchoolStudentId = 9, SchoolNameSnapshot = "Greenfield Academy", CourseNameSnapshot = "Creative Writing", CourseDescriptionSnapshot = "Writing techniques across common genres.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt },
                new Enrollment { Id = 19, CourseId = 10, SchoolStudentId = 9, SchoolNameSnapshot = "Hillcrest Education Centre", CourseNameSnapshot = "Legacy Office Applications", CourseDescriptionSnapshot = "Archived office applications programme.", CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Citizen 009", CitizenEmailSnapshot = "citizen009@example.com", CitizenPhoneNumberSnapshot = "+6590000009", AccountNumberSnapshot = "EDU-2026-00000000009", CreatedAt = createdAt });

            return modelBuilder;
        }
    }
}