using Enums;
using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class FasSeedBuilder : ISeedBuilder
    {
        public int Priority => 125;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;
            var approvedAt = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc);

            modelBuilder.Entity<FasScheme>().HasData(
                new FasScheme { Id = 1, SchoolId = 1, Status = FasSchemeStatus.Active, SchemeCode = "FAS-001", SchemeName = "Household Income Subsidy", Description = "Support for students from lower-income households.", DurationInMonths = 6, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 2, SchoolId = 2, Status = FasSchemeStatus.Active, SchemeCode = "FAS-002", SchemeName = "Transport Assistance", Description = "Transport support for eligible students.", DurationInMonths = 3, SubsidyType = FasSubsidyType.FixedAmount, PublishedAt = new DateTime(2026, 1, 2, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 3, SchoolId = 3, Status = FasSchemeStatus.Active, SchemeCode = "FAS-003", SchemeName = "Study Grant", Description = "Course and misc fee assistance.", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, IsPerComponent = true, PublishedAt = new DateTime(2026, 1, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 4, SchoolId = 4, Status = FasSchemeStatus.Draft, SchemeCode = "FAS-004", SchemeName = "Meal Subsidy", Description = "Draft meal support programme.", DurationInMonths = 6, SubsidyType = FasSubsidyType.Percent, CreatedAt = createdAt },
                new FasScheme { Id = 5, SchoolId = 5, Status = FasSchemeStatus.Active, SchemeCode = "FAS-005", SchemeName = "Digital Device Grant", Description = "Support for digital learning devices.", DurationInMonths = 9, SubsidyType = FasSubsidyType.FixedAmount, PublishedAt = new DateTime(2026, 1, 5, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 6, SchoolId = 6, Status = FasSchemeStatus.Inactive, SchemeCode = "FAS-006", SchemeName = "Uniform Grant", Description = "Inactive uniform support programme.", DurationInMonths = 3, SubsidyType = FasSubsidyType.FixedAmount, PublishedAt = new DateTime(2026, 1, 6, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 7, SchoolId = 7, Status = FasSchemeStatus.Active, SchemeCode = "FAS-007", SchemeName = "Special Needs Support", Description = "Support for students with special learning needs.", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, IsPerComponent = true, PublishedAt = new DateTime(2026, 1, 7, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 8, SchoolId = 8, Status = FasSchemeStatus.Active, SchemeCode = "FAS-008", SchemeName = "Learning Materials Grant", Description = "Support for textbooks and materials.", DurationInMonths = 6, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 8, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 9, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-009", SchemeName = "Emergency Financial Aid", Description = "Short term emergency support.", DurationInMonths = 3, SubsidyType = FasSubsidyType.FixedAmount, PublishedAt = new DateTime(2026, 1, 9, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 10, SchoolId = 10, Status = FasSchemeStatus.Active, SchemeCode = "FAS-010", SchemeName = "STEM Programme Grant", Description = "Support for STEM related courses.", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 11, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-011", SchemeName = "School 9 Scheme 11", Description = "Auto generated scheme 11 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 12, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-012", SchemeName = "School 9 Scheme 12", Description = "Auto generated scheme 12 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 13, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-013", SchemeName = "School 9 Scheme 13", Description = "Auto generated scheme 13 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 14, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-014", SchemeName = "School 9 Scheme 14", Description = "Auto generated scheme 14 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 15, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-015", SchemeName = "School 9 Scheme 15", Description = "Auto generated scheme 15 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 16, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-016", SchemeName = "School 9 Scheme 16", Description = "Auto generated scheme 16 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 17, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-017", SchemeName = "School 9 Scheme 17", Description = "Auto generated scheme 17 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 18, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-018", SchemeName = "School 9 Scheme 18", Description = "Auto generated scheme 18 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 19, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-019", SchemeName = "School 9 Scheme 19", Description = "Auto generated scheme 19 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 20, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-020", SchemeName = "School 9 Scheme 20", Description = "Auto generated scheme 20 for school 9", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 21, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-021", SchemeName = "School 9 Scheme 21 (For F7.2 Test)", Description = "Auto generated scheme 21 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 22, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-022", SchemeName = "School 9 Scheme 22 (For F7.2 Test)", Description = "Auto generated scheme 22 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 23, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-023", SchemeName = "School 9 Scheme 23 (For F7.2 Test)", Description = "Auto generated scheme 23 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 24, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-024", SchemeName = "School 9 Scheme 24 (For F7.2 Test)", Description = "Auto generated scheme 24 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 25, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-025", SchemeName = "School 9 Scheme 25 (For F7.2 Test)", Description = "Auto generated scheme 25 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 26, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-026", SchemeName = "School 9 Scheme 26 (For F7.2 Test)", Description = "Auto generated scheme 26 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 27, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-027", SchemeName = "School 9 Scheme 27 (For F7.2 Test)", Description = "Auto generated scheme 27 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 28, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-028", SchemeName = "School 9 Scheme 28 (For F7.2 Test)", Description = "Auto generated scheme 28 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 29, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-029", SchemeName = "School 9 Scheme 29 (For F7.2 Test)", Description = "Auto generated scheme 29 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasScheme { Id = 30, SchoolId = 9, Status = FasSchemeStatus.Active, SchemeCode = "FAS-030", SchemeName = "School 9 Scheme 30 (For F7.2 Test)", Description = "Auto generated scheme 30 for school 9 test F7.2", DurationInMonths = 12, SubsidyType = FasSubsidyType.Percent, PublishedAt = new DateTime(2026, 1, 10, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

            modelBuilder.Entity<FasSchemeConditionGroup>().HasData(
                Enumerable.Range(1, 30).Select(id => new FasSchemeConditionGroup { Id = id, FasSchemeId = id, ParentGroupId = null, LogicalOperator = TopupLogicalOperator.And, DisplayOrder = id, CreatedAt = createdAt }).ToArray());

            modelBuilder.Entity<FasSchemeCondition>().HasData(
                new FasSchemeCondition { Id = 1, GroupId = 1, Field = FasConditionField.PerCapitaIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 750m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 2, GroupId = 2, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 3500m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 3, GroupId = 3, Field = FasConditionField.StudentNationality, Operator = FasConditionOperator.Equal, ValueText = "Singapore", DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 4, GroupId = 4, Field = FasConditionField.StudentAge, Operator = FasConditionOperator.Between, ValueNumber = 16m, ValueNumberTo = 30m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 5, GroupId = 5, Field = FasConditionField.GuardianNationality, Operator = FasConditionOperator.Equal, ValueText = "Singapore", DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 6, GroupId = 6, Field = FasConditionField.PerCapitaIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 1000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 7, GroupId = 7, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 5000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 8, GroupId = 8, Field = FasConditionField.StudentNationality, Operator = FasConditionOperator.Equal, ValueText = "Singapore", DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 9, GroupId = 9, Field = FasConditionField.PerCapitaIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 1200m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 10, GroupId = 10, Field = FasConditionField.StudentAge, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 25m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 11, GroupId = 11, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 12, GroupId = 12, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 13, GroupId = 13, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 14, GroupId = 14, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 15, GroupId = 15, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 16, GroupId = 16, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 17, GroupId = 17, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 18, GroupId = 18, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 19, GroupId = 19, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 20, GroupId = 20, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 21, GroupId = 21, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 22, GroupId = 22, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 23, GroupId = 23, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 24, GroupId = 24, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 25, GroupId = 25, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 26, GroupId = 26, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 27, GroupId = 27, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 28, GroupId = 28, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 29, GroupId = 29, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeCondition { Id = 30, GroupId = 30, Field = FasConditionField.GrossHouseholdIncome, Operator = FasConditionOperator.LessThanOrEqual, ValueNumber = 10000m, DisplayOrder = 1, CreatedAt = createdAt });

            modelBuilder.Entity<FasSchemeTier>().HasData(
                new FasSchemeTier { Id = 1, FasSchemeId = 1, TierName = "Tier 1", MaxPerCapitaIncome = 750m, SubsidyValue = 75m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 2, FasSchemeId = 2, TierName = "Tier 1", MaxPerCapitaIncome = 900m, SubsidyValue = 300m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 3, FasSchemeId = 3, TierName = "Tier 1", MaxPerCapitaIncome = 690m, CourseFeeSubsidyValue = 100m, MiscFeeSubsidyValue = 50m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 4, FasSchemeId = 4, TierName = "Tier 1", MaxPerCapitaIncome = 800m, SubsidyValue = 50m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 5, FasSchemeId = 5, TierName = "Tier 1", MaxPerCapitaIncome = 1000m, SubsidyValue = 500m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 6, FasSchemeId = 6, TierName = "Tier 1", MaxPerCapitaIncome = 750m, SubsidyValue = 200m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 7, FasSchemeId = 7, TierName = "Tier 1", MaxPerCapitaIncome = 1500m, CourseFeeSubsidyValue = 75m, MiscFeeSubsidyValue = 75m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 8, FasSchemeId = 8, TierName = "Tier 1", MaxPerCapitaIncome = 850m, SubsidyValue = 40m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 9, FasSchemeId = 9, TierName = "Tier 1", MaxPerCapitaIncome = 1200m, SubsidyValue = 250m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 10, FasSchemeId = 10, TierName = "Tier 1", MaxPerCapitaIncome = 1000m, SubsidyValue = 60m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 11, FasSchemeId = 11, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 12, FasSchemeId = 12, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 13, FasSchemeId = 13, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 14, FasSchemeId = 14, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 15, FasSchemeId = 15, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 16, FasSchemeId = 16, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 17, FasSchemeId = 17, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 18, FasSchemeId = 18, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 19, FasSchemeId = 19, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 20, FasSchemeId = 20, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 21, FasSchemeId = 21, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 22, FasSchemeId = 22, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 23, FasSchemeId = 23, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 24, FasSchemeId = 24, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 25, FasSchemeId = 25, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 26, FasSchemeId = 26, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 27, FasSchemeId = 27, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 28, FasSchemeId = 28, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 29, FasSchemeId = 29, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt },
                new FasSchemeTier { Id = 30, FasSchemeId = 30, TierName = "Tier 1", MaxPerCapitaIncome = 10000m, SubsidyValue = 100m, DisplayOrder = 1, CreatedAt = createdAt });

            modelBuilder.Entity<FasSchemeRequiredDocument>().HasData(
                Enumerable.Range(1, 30).Select(id => new FasSchemeRequiredDocument { Id = id, FasSchemeId = id, DocumentName = id % 2 == 0 ? "Income Statement" : "Recent Payslip", TemplateFileKey = $"fas/templates/document-{id}.pdf", DisplayOrder = 1, CreatedAt = createdAt }).ToArray());

            var schemeCourses = Enumerable.Range(1, 30)
                .Select(id => new FasSchemeCourse
                {
                    Id = id,
                    FasSchemeId = id,
                    CourseId = id,
                    CreatedAt = createdAt
                })
                .ToList();
            var schemeCourseId = 31;
            for (var courseId = 31; courseId <= 100; courseId++)
            {
                var schoolId = ((courseId - 11) / 9) + 1;
                schemeCourses.Add(new FasSchemeCourse
                {
                    Id = schemeCourseId++,
                    FasSchemeId = schoolId,
                    CourseId = courseId,
                    CreatedAt = createdAt
                });
            }

            modelBuilder.Entity<FasSchemeCourse>().HasData(schemeCourses);

            modelBuilder.Entity<FasApplication>().HasData(
                new FasApplication { Id = 1, FasSchemeId = 1, SchoolStudentId = 1, RecommendedTierId = 1, ApprovedTierId = 1, ApplicationNumber = "FASAPP-20260101-A1B2C3D", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 18, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.SingaporeCitizen, GrossHouseholdIncomeSnapshot = 2500m, HouseholdMemberCountSnapshot = 4, PerCapitaIncomeSnapshot = 625m, RecommendationReason = "PCI <= 750", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 6, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(6), CreatedAt = createdAt },
                new FasApplication { Id = 2, FasSchemeId = 2, SchoolStudentId = 2, RecommendedTierId = 2, ApprovedTierId = 2, ApplicationNumber = "FASAPP-20260102-E4F5G6H", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 3000m, HouseholdMemberCountSnapshot = 4, PerCapitaIncomeSnapshot = 750m, RecommendationReason = "GHI <= 3500", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 3, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(3), CreatedAt = createdAt },
                new FasApplication { Id = 3, FasSchemeId = 3, SchoolStudentId = 3, RecommendedTierId = 3, ApprovedTierId = 3, ApplicationNumber = "FASAPP-20260103-I7J8K9L", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 19, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.SingaporeCitizen, GrossHouseholdIncomeSnapshot = 2200m, HouseholdMemberCountSnapshot = 5, PerCapitaIncomeSnapshot = 440m, RecommendationReason = "Singapore citizen and PCI <= 690", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 12, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(12), CreatedAt = createdAt },
                new FasApplication { Id = 4, FasSchemeId = 4, SchoolStudentId = 4, RecommendedTierId = 4, ApplicationNumber = "FASAPP-20260104-M1N2P3Q", Status = FasApplicationStatus.Pending, StudentAgeSnapshot = 20, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 3600m, HouseholdMemberCountSnapshot = 4, PerCapitaIncomeSnapshot = 900m, RecommendationReason = "Pending admin review", CreatedAt = createdAt },
                new FasApplication { Id = 5, FasSchemeId = 5, SchoolStudentId = 5, RecommendedTierId = 5, ApplicationNumber = "FASAPP-20260105-R4S5T6U", Status = FasApplicationStatus.Rejected, StudentAgeSnapshot = 21, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 7000m, HouseholdMemberCountSnapshot = 4, PerCapitaIncomeSnapshot = 1750m, RecommendationReason = "No tier matched", RejectionReason = "Income exceeds supported threshold.", CreatedAt = createdAt },
                new FasApplication { Id = 6, FasSchemeId = 6, SchoolStudentId = 6, RecommendedTierId = 6, ApplicationNumber = "FASAPP-20260106-V7W8X9Y", Status = FasApplicationStatus.Withdrawn, StudentAgeSnapshot = 18, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.SingaporeCitizen, GrossHouseholdIncomeSnapshot = 2800m, HouseholdMemberCountSnapshot = 5, PerCapitaIncomeSnapshot = 560m, RecommendationReason = "Student withdrew before review", WithdrawnAt = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasApplication { Id = 7, FasSchemeId = 7, SchoolStudentId = 7, RecommendedTierId = 7, ApprovedTierId = 7, ApplicationNumber = "FASAPP-20260107-Z1A2B3C", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 16, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.SingaporeCitizen, GrossHouseholdIncomeSnapshot = 4800m, HouseholdMemberCountSnapshot = 4, PerCapitaIncomeSnapshot = 1200m, RecommendationReason = "Special needs support threshold matched", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 12, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(12), CreatedAt = createdAt },
                new FasApplication { Id = 8, FasSchemeId = 8, SchoolStudentId = 8, RecommendedTierId = 8, ApprovedTierId = 8, ApplicationNumber = "FASAPP-20260108-D4E5F6G", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 22, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 3200m, HouseholdMemberCountSnapshot = 5, PerCapitaIncomeSnapshot = 640m, RecommendationReason = "PCI <= 850", ApprovedAt = new DateTime(2025, 6, 1, 0, 0, 0, DateTimeKind.Utc), ApprovedByUserId = 1, DurationInMonthsSnapshot = 6, ValidityStartDate = new DateTime(2025, 6, 1, 0, 0, 0, DateTimeKind.Utc), ValidityEndDate = new DateTime(2025, 12, 1, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasApplication { Id = 9, FasSchemeId = 9, SchoolStudentId = 9, RecommendedTierId = 9, ApplicationNumber = "FASAPP-20260109-H7J8K9L", Status = FasApplicationStatus.Pending, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Emergency aid review required", CreatedAt = createdAt },
                new FasApplication { Id = 10, FasSchemeId = 10, SchoolStudentId = 10, RecommendedTierId = 10, ApprovedTierId = 10, ApplicationNumber = "FASAPP-20260110-M1N2P3Q", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 18, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.SingaporeCitizen, GrossHouseholdIncomeSnapshot = 3900m, HouseholdMemberCountSnapshot = 5, PerCapitaIncomeSnapshot = 780m, RecommendationReason = "PCI <= 1000", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 12, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(12), CreatedAt = createdAt },
                new FasApplication { Id = 11, FasSchemeId = 11, SchoolStudentId = 9, RecommendedTierId = 11, ApplicationNumber = "FASAPP-20260111-A1B2C11", Status = FasApplicationStatus.Pending, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Pending admin review", CreatedAt = createdAt },
                new FasApplication { Id = 12, FasSchemeId = 12, SchoolStudentId = 9, RecommendedTierId = 12, ApplicationNumber = "FASAPP-20260112-A1B2C12", Status = FasApplicationStatus.Pending, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Pending admin review", CreatedAt = createdAt },
                new FasApplication { Id = 13, FasSchemeId = 13, SchoolStudentId = 9, RecommendedTierId = 13, ApplicationNumber = "FASAPP-20260113-A1B2C13", Status = FasApplicationStatus.Pending, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Pending admin review", CreatedAt = createdAt },
                new FasApplication { Id = 14, FasSchemeId = 14, SchoolStudentId = 9, RecommendedTierId = 14, ApprovedTierId = 14, ApplicationNumber = "FASAPP-20260114-D4E5F14", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "PCI matches", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 6, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(6), CreatedAt = createdAt },
                new FasApplication { Id = 15, FasSchemeId = 15, SchoolStudentId = 9, RecommendedTierId = 15, ApprovedTierId = 15, ApplicationNumber = "FASAPP-20260115-D4E5F15", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "PCI matches", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 6, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(6), CreatedAt = createdAt },
                new FasApplication { Id = 16, FasSchemeId = 16, SchoolStudentId = 9, RecommendedTierId = 16, ApprovedTierId = 16, ApplicationNumber = "FASAPP-20260116-D4E5F16", Status = FasApplicationStatus.Approved, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "PCI matches", ApprovedAt = approvedAt, ApprovedByUserId = 1, DurationInMonthsSnapshot = 6, ValidityStartDate = approvedAt, ValidityEndDate = approvedAt.AddMonths(6), CreatedAt = createdAt },
                new FasApplication { Id = 17, FasSchemeId = 17, SchoolStudentId = 9, RecommendedTierId = 17, ApplicationNumber = "FASAPP-20260117-G7H8I17", Status = FasApplicationStatus.Rejected, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 12000m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 4000m, RecommendationReason = "No tier matched", RejectionReason = "Income exceeds supported threshold.", CreatedAt = createdAt },
                new FasApplication { Id = 18, FasSchemeId = 18, SchoolStudentId = 9, RecommendedTierId = 18, ApplicationNumber = "FASAPP-20260118-G7H8I18", Status = FasApplicationStatus.Rejected, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 12000m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 4000m, RecommendationReason = "No tier matched", RejectionReason = "The income proof document is invalid or blurry.", CreatedAt = createdAt },
                new FasApplication { Id = 19, FasSchemeId = 19, SchoolStudentId = 9, RecommendedTierId = 19, ApplicationNumber = "FASAPP-20260119-G7H8I19", Status = FasApplicationStatus.Rejected, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 12000m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 4000m, RecommendationReason = "No tier matched", RejectionReason = "The student does not meet the eligibility conditions for this scheme.", CreatedAt = createdAt },
                new FasApplication { Id = 20, FasSchemeId = 20, SchoolStudentId = 9, RecommendedTierId = 20, ApplicationNumber = "FASAPP-20260120-J1K2L20", Status = FasApplicationStatus.Withdrawn, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Student withdrew", WithdrawnAt = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasApplication { Id = 21, FasSchemeId = 17, SchoolStudentId = 9, RecommendedTierId = 17, ApplicationNumber = "FASAPP-20260121-J1K2L21", Status = FasApplicationStatus.Withdrawn, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Student withdrew", WithdrawnAt = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt },
                new FasApplication { Id = 22, FasSchemeId = 18, SchoolStudentId = 9, RecommendedTierId = 18, ApplicationNumber = "FASAPP-20260122-J1K2L22", Status = FasApplicationStatus.Withdrawn, StudentAgeSnapshot = 17, StudentNationalitySnapshot = NationalityCategory.SingaporeCitizen, GuardianNationalitySnapshot = NationalityCategory.Other, GrossHouseholdIncomeSnapshot = 2600m, HouseholdMemberCountSnapshot = 3, PerCapitaIncomeSnapshot = 866.67m, RecommendationReason = "Student withdrew", WithdrawnAt = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), CreatedAt = createdAt });

            modelBuilder.Entity<FasApplicationDocument>().HasData(
                Enumerable.Range(1, 22).Select(id => new FasApplicationDocument { Id = id, FasApplicationId = id, FasSchemeRequiredDocumentId = id, DocumentNameSnapshot = id % 2 == 0 ? "Income Statement" : "Recent Payslip", FileKey = $"fas/applications/{id}/document.pdf", FileName = $"fas-application-{id}.pdf", CreatedAt = createdAt }).ToArray());

            modelBuilder.Entity<FasTierOverrideHistory>().HasData(
                Enumerable.Range(1, 22).Select(id => new FasTierOverrideHistory { Id = id, FasApplicationId = id, OldTierId = id, NewTierId = id, ModifiedByUserId = 1, ModifiedAt = new DateTime(2026, 6, id > 28 ? 1 : id, 0, 0, 0, DateTimeKind.Utc), Reason = "Seed audit trail for tier review.", CreatedAt = createdAt }).ToArray());

            return modelBuilder;
        }
    }
}
