using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class PaymentSeedBuilder : ISeedBuilder
    {
        public int Priority => 140;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<Payment>().HasData(
                new Payment { Id = 1, EducationCreditTransactionId = 1, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(1), CitizenNricSnapshot = SingaporeNricUtil.Generate(1), CitizenFullNameSnapshot = "Sterling Quach", TotalAmount = 124m, CreatedAt = createdAt },
                new Payment { Id = 2, EducationCreditTransactionId = 2, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(2), CitizenNricSnapshot = SingaporeNricUtil.Generate(2), CitizenFullNameSnapshot = "Amelia Tan", TotalAmount = 128m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 2, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00002" },
                new Payment { Id = 3, EducationCreditTransactionId = 3, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(3), CitizenNricSnapshot = SingaporeNricUtil.Generate(3), CitizenFullNameSnapshot = "Marcus Lim", TotalAmount = 132m, CreatedAt = createdAt },
                new Payment { Id = 4, EducationCreditTransactionId = 4, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(4), CitizenNricSnapshot = SingaporeNricUtil.Generate(4), CitizenFullNameSnapshot = "Priya Nair", TotalAmount = 136m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00004" },
                new Payment { Id = 5, EducationCreditTransactionId = 5, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(5), CitizenNricSnapshot = SingaporeNricUtil.Generate(5), CitizenFullNameSnapshot = "Ethan Koh", TotalAmount = 140m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 5, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 6, EducationCreditTransactionId = 6, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(6), CitizenNricSnapshot = SingaporeNricUtil.Generate(6), CitizenFullNameSnapshot = "Hannah Lee", TotalAmount = 144m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00006" },
                new Payment { Id = 7, EducationCreditTransactionId = 7, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(7), CitizenNricSnapshot = SingaporeNricUtil.Generate(7), CitizenFullNameSnapshot = "Daniel Wong", TotalAmount = 148m, CreatedAt = createdAt },
                new Payment { Id = 8, EducationCreditTransactionId = 8, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(8), CitizenNricSnapshot = SingaporeNricUtil.Generate(8), CitizenFullNameSnapshot = "Sofia Chen", TotalAmount = 152m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 8, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00008" },
                new Payment { Id = 9, EducationCreditTransactionId = 9, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(9), CitizenNricSnapshot = SingaporeNricUtil.Generate(9), CitizenFullNameSnapshot = "Lucas Nguyen", TotalAmount = 156m, CreatedAt = createdAt },
                new Payment { Id = 10, EducationCreditTransactionId = 10, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(10), CitizenNricSnapshot = SingaporeNricUtil.Generate(10), CitizenFullNameSnapshot = "Maya Rahman", TotalAmount = 160m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00010" },
                new Payment { Id = 11, EducationCreditTransactionId = 11, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(11), CitizenNricSnapshot = SingaporeNricUtil.Generate(11), CitizenFullNameSnapshot = "Noah Teo", TotalAmount = 164m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 11, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 12, EducationCreditTransactionId = 12, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(12), CitizenNricSnapshot = SingaporeNricUtil.Generate(12), CitizenFullNameSnapshot = "Aisha Fernandez", TotalAmount = 168m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00012" },
                new Payment { Id = 13, EducationCreditTransactionId = 13, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(13), CitizenNricSnapshot = SingaporeNricUtil.Generate(13), CitizenFullNameSnapshot = "Ryan Chua", TotalAmount = 172m, CreatedAt = createdAt },
                new Payment { Id = 14, EducationCreditTransactionId = 14, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(14), CitizenNricSnapshot = SingaporeNricUtil.Generate(14), CitizenFullNameSnapshot = "Chloe Goh", TotalAmount = 176m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 14, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00014" },
                new Payment { Id = 15, EducationCreditTransactionId = 15, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(15), CitizenNricSnapshot = SingaporeNricUtil.Generate(15), CitizenFullNameSnapshot = "Irfan Hassan", TotalAmount = 180m, CreatedAt = createdAt },
                new Payment { Id = 16, EducationCreditTransactionId = 16, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(16), CitizenNricSnapshot = SingaporeNricUtil.Generate(16), CitizenFullNameSnapshot = "Natalie Seah", TotalAmount = 184m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00016" },
                new Payment { Id = 17, EducationCreditTransactionId = 17, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(17), CitizenNricSnapshot = SingaporeNricUtil.Generate(17), CitizenFullNameSnapshot = "Alina Ang", TotalAmount = 188m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 17, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 18, EducationCreditTransactionId = 18, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(18), CitizenNricSnapshot = SingaporeNricUtil.Generate(18), CitizenFullNameSnapshot = "Benjamin Bala", TotalAmount = 192m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00018" },
                new Payment { Id = 19, EducationCreditTransactionId = 19, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(19), CitizenNricSnapshot = SingaporeNricUtil.Generate(19), CitizenFullNameSnapshot = "Clara Chew", TotalAmount = 196m, CreatedAt = createdAt },
                new Payment { Id = 20, EducationCreditTransactionId = 20, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(20), CitizenNricSnapshot = SingaporeNricUtil.Generate(20), CitizenFullNameSnapshot = "Darius Das", TotalAmount = 200m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 20, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00020" },
                new Payment { Id = 21, EducationCreditTransactionId = 21, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(21), CitizenNricSnapshot = SingaporeNricUtil.Generate(21), CitizenFullNameSnapshot = "Elena Eng", TotalAmount = 204m, CreatedAt = createdAt },
                new Payment { Id = 22, EducationCreditTransactionId = 22, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(22), CitizenNricSnapshot = SingaporeNricUtil.Generate(22), CitizenFullNameSnapshot = "Farhan Foo", TotalAmount = 208m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00022" },
                new Payment { Id = 23, EducationCreditTransactionId = 23, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(23), CitizenNricSnapshot = SingaporeNricUtil.Generate(23), CitizenFullNameSnapshot = "Grace Gan", TotalAmount = 212m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 23, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 24, EducationCreditTransactionId = 24, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(24), CitizenNricSnapshot = SingaporeNricUtil.Generate(24), CitizenFullNameSnapshot = "Haruto Ho", TotalAmount = 216m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00024" },
                new Payment { Id = 25, EducationCreditTransactionId = 25, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(25), CitizenNricSnapshot = SingaporeNricUtil.Generate(25), CitizenFullNameSnapshot = "Isabelle Ismail", TotalAmount = 220m, CreatedAt = createdAt },
                new Payment { Id = 26, EducationCreditTransactionId = 26, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(26), CitizenNricSnapshot = SingaporeNricUtil.Generate(26), CitizenFullNameSnapshot = "Jasper Jeyaratnam", TotalAmount = 224m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 26, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00026" },
                new Payment { Id = 27, EducationCreditTransactionId = 27, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(27), CitizenNricSnapshot = SingaporeNricUtil.Generate(27), CitizenFullNameSnapshot = "Keira Kwek", TotalAmount = 228m, CreatedAt = createdAt },
                new Payment { Id = 28, EducationCreditTransactionId = 28, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(28), CitizenNricSnapshot = SingaporeNricUtil.Generate(28), CitizenFullNameSnapshot = "Leon Lim", TotalAmount = 232m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00028" },
                new Payment { Id = 29, EducationCreditTransactionId = 29, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(29), CitizenNricSnapshot = SingaporeNricUtil.Generate(29), CitizenFullNameSnapshot = "Mei Lin Mohamed", TotalAmount = 236m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 30, EducationCreditTransactionId = 30, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(30), CitizenNricSnapshot = SingaporeNricUtil.Generate(30), CitizenFullNameSnapshot = "Nathan Ng", TotalAmount = 240m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00030" },
                new Payment { Id = 31, EducationCreditTransactionId = 31, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(31), CitizenNricSnapshot = SingaporeNricUtil.Generate(31), CitizenFullNameSnapshot = "Olivia Ong", TotalAmount = 244m, CreatedAt = createdAt },
                new Payment { Id = 32, EducationCreditTransactionId = 32, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(32), CitizenNricSnapshot = SingaporeNricUtil.Generate(32), CitizenFullNameSnapshot = "Pranav Pillai", TotalAmount = 248m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 4, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00032" },
                new Payment { Id = 33, EducationCreditTransactionId = 33, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(33), CitizenNricSnapshot = SingaporeNricUtil.Generate(33), CitizenFullNameSnapshot = "Qistina Quek", TotalAmount = 252m, CreatedAt = createdAt },
                new Payment { Id = 34, EducationCreditTransactionId = 34, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(34), CitizenNricSnapshot = SingaporeNricUtil.Generate(34), CitizenFullNameSnapshot = "Rafael Rao", TotalAmount = 256m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00034" },
                new Payment { Id = 35, EducationCreditTransactionId = 35, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(35), CitizenNricSnapshot = SingaporeNricUtil.Generate(35), CitizenFullNameSnapshot = "Selina Sim", TotalAmount = 260m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 7, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 36, EducationCreditTransactionId = 36, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(36), CitizenNricSnapshot = SingaporeNricUtil.Generate(36), CitizenFullNameSnapshot = "Terence Tan", TotalAmount = 264m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00036" },
                new Payment { Id = 37, EducationCreditTransactionId = 37, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(37), CitizenNricSnapshot = SingaporeNricUtil.Generate(37), CitizenFullNameSnapshot = "Umairah Uddin", TotalAmount = 268m, CreatedAt = createdAt },
                new Payment { Id = 38, EducationCreditTransactionId = 38, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(38), CitizenNricSnapshot = SingaporeNricUtil.Generate(38), CitizenFullNameSnapshot = "Victor Vasquez", TotalAmount = 272m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 10, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00038" },
                new Payment { Id = 39, EducationCreditTransactionId = 39, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(39), CitizenNricSnapshot = SingaporeNricUtil.Generate(39), CitizenFullNameSnapshot = "Wen Jie Wong", TotalAmount = 276m, CreatedAt = createdAt },
                new Payment { Id = 40, EducationCreditTransactionId = 40, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(40), CitizenNricSnapshot = SingaporeNricUtil.Generate(40), CitizenFullNameSnapshot = "Xavier Xu", TotalAmount = 280m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00040" },
                new Payment { Id = 41, EducationCreditTransactionId = 41, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(41), CitizenNricSnapshot = SingaporeNricUtil.Generate(41), CitizenFullNameSnapshot = "Yasmin Yeo", TotalAmount = 284m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 13, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 42, EducationCreditTransactionId = 42, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(42), CitizenNricSnapshot = SingaporeNricUtil.Generate(42), CitizenFullNameSnapshot = "Zachary Zainal", TotalAmount = 288m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00042" },
                new Payment { Id = 43, EducationCreditTransactionId = 43, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(43), CitizenNricSnapshot = SingaporeNricUtil.Generate(43), CitizenFullNameSnapshot = "Adeline Ang", TotalAmount = 292m, CreatedAt = createdAt },
                new Payment { Id = 44, EducationCreditTransactionId = 44, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(44), CitizenNricSnapshot = SingaporeNricUtil.Generate(44), CitizenFullNameSnapshot = "Brandon Bala", TotalAmount = 296m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 16, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00044" },
                new Payment { Id = 45, EducationCreditTransactionId = 45, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(45), CitizenNricSnapshot = SingaporeNricUtil.Generate(45), CitizenFullNameSnapshot = "Celeste Chew", TotalAmount = 300m, CreatedAt = createdAt },
                new Payment { Id = 46, EducationCreditTransactionId = 46, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(46), CitizenNricSnapshot = SingaporeNricUtil.Generate(46), CitizenFullNameSnapshot = "Damien Das", TotalAmount = 304m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00046" },
                new Payment { Id = 47, EducationCreditTransactionId = 47, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(47), CitizenNricSnapshot = SingaporeNricUtil.Generate(47), CitizenFullNameSnapshot = "Evelyn Eng", TotalAmount = 308m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 19, 0, 0, 0, DateTimeKind.Utc) },
                new Payment { Id = 48, EducationCreditTransactionId = 48, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Failed, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(48), CitizenNricSnapshot = SingaporeNricUtil.Generate(48), CitizenFullNameSnapshot = "Faris Foo", TotalAmount = 312m, CreatedAt = createdAt, ExternalReference = "PAY-EXT-00048" },
                new Payment { Id = 49, EducationCreditTransactionId = 49, PaymentMethod = PaymentMethod.EducationBalance, Status = PaymentStatus.Pending, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(49), CitizenNricSnapshot = SingaporeNricUtil.Generate(49), CitizenFullNameSnapshot = "Giselle Gan", TotalAmount = 316m, CreatedAt = createdAt },
                new Payment { Id = 50, EducationCreditTransactionId = 50, PaymentMethod = PaymentMethod.OnlinePayment, Status = PaymentStatus.Succeeded, AccountNumberSnapshot = SeedAccountNumberUtil.Generate(50), CitizenNricSnapshot = SingaporeNricUtil.Generate(50), CitizenFullNameSnapshot = "Haziq Ho", TotalAmount = 320m, CreatedAt = createdAt, PaidAt = new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc), ExternalReference = "PAY-EXT-00050" });

            return modelBuilder;
        }
    }
}
