using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class TopupExecutionSeedBuilder : ISeedBuilder
    {
        public int Priority => 200;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<TopupExecution>().HasData(
                new TopupExecution { Id = 1, ExecutionCode = "TOPUP-RUN-001", SourceType = TopupExecutionSourceType.System, SystemTopupId = 1, ScheduleTopUpId = null, IdempotencyKey = "topup-run-001", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 85m, TopupNameSnapshot = "Monthly Learning Credit Boost", TopupAmountSnapshot = 85m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(1), CreatedBy = 2 },
                new TopupExecution { Id = 2, ExecutionCode = "TOPUP-RUN-002", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 2, IdempotencyKey = "topup-run-002", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 95m, TopupNameSnapshot = "Monthly Meal Allowance", TopupAmountSnapshot = 95m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(2), CreatedBy = 2 },
                new TopupExecution { Id = 3, ExecutionCode = "TOPUP-RUN-003", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-003", ManualAmount = 105m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 105m, TopupNameSnapshot = "Manual Account Adjustment", TopupAmountSnapshot = 105m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(3), CreatedBy = 2 },
                new TopupExecution { Id = 4, ExecutionCode = "TOPUP-RUN-004", SourceType = TopupExecutionSourceType.System, SystemTopupId = 4, ScheduleTopUpId = null, IdempotencyKey = "topup-run-004", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 0, FailedCount = 1, TotalExecutedAmount = 0m, TopupNameSnapshot = "Back-to-School Credit", TopupAmountSnapshot = 115m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(4), CreatedBy = 2 },
                new TopupExecution { Id = 5, ExecutionCode = "TOPUP-RUN-005", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 5, IdempotencyKey = "topup-run-005", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 125m, TopupNameSnapshot = "Monthly Attendance Support", TopupAmountSnapshot = 125m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(5), CreatedBy = 2 },
                new TopupExecution { Id = 6, ExecutionCode = "TOPUP-RUN-006", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-006", ManualAmount = 135m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 135m, TopupNameSnapshot = "Manual Transport Reimbursement", TopupAmountSnapshot = 135m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(6), CreatedBy = 2 },
                new TopupExecution { Id = 7, ExecutionCode = "TOPUP-RUN-007", SourceType = TopupExecutionSourceType.System, SystemTopupId = 7, ScheduleTopUpId = null, IdempotencyKey = "topup-run-007", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 145m, TopupNameSnapshot = "STEM Enrichment Credit", TopupAmountSnapshot = 145m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(7), CreatedBy = 2 },
                new TopupExecution { Id = 8, ExecutionCode = "TOPUP-RUN-008", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 8, IdempotencyKey = "topup-run-008", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 0, FailedCount = 1, TotalExecutedAmount = 0m, TopupNameSnapshot = "Monthly Commuter Credit", TopupAmountSnapshot = 155m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(8), CreatedBy = 2 },
                new TopupExecution { Id = 9, ExecutionCode = "TOPUP-RUN-009", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-009", ManualAmount = 165m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 165m, TopupNameSnapshot = "Manual Materials Reimbursement", TopupAmountSnapshot = 165m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(9), CreatedBy = 2 },
                new TopupExecution { Id = 10, ExecutionCode = "TOPUP-RUN-010", SourceType = TopupExecutionSourceType.System, SystemTopupId = 10, ScheduleTopUpId = null, IdempotencyKey = "topup-run-010", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 175m, TopupNameSnapshot = "Holiday Programme Support", TopupAmountSnapshot = 175m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(10), CreatedBy = 2 });

            return modelBuilder;
        }
    }
}
