using Models;
using Persistence.Seeding.Constants;

namespace Persistence.Seeding
{
    public sealed class TopupExecutionSeedBuilder : ISeedBuilder
    {
        public int Priority => 200;

        public ModelBuilder Seed(ModelBuilder modelBuilder)
        {
            var createdAt = SeedDataConstants.CreatedAt;

            modelBuilder.Entity<TopupExecution>().HasData(
                new TopupExecution { Id = 1, ExecutionCode = "TOPUP-RUN-001", SourceType = TopupExecutionSourceType.System, SystemTopupId = 1, ScheduleTopUpId = null, IdempotencyKey = "topup-run-001", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 85m, TopupNameSnapshot = "Monthly Learning Credit Boost", TopupAmountSnapshot = 85m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(1), CreatedBy = 2 },
                new TopupExecution { Id = 2, ExecutionCode = "TOPUP-RUN-002", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 2, IdempotencyKey = "topup-run-002", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 95m, TopupNameSnapshot = "Monthly Meal Allowance", TopupAmountSnapshot = 95m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(2), CreatedBy = 2 },
                new TopupExecution { Id = 3, ExecutionCode = "TOPUP-RUN-003", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-003", ManualAmount = 105m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 105m, TopupNameSnapshot = "Manual Account Adjustment", TopupAmountSnapshot = 105m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(3), CreatedBy = 2 },
                new TopupExecution { Id = 4, ExecutionCode = "TOPUP-RUN-004", SourceType = TopupExecutionSourceType.System, SystemTopupId = 4, ScheduleTopUpId = null, IdempotencyKey = "topup-run-004", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 0, FailedCount = 1, TotalExecutedAmount = 0m, TopupNameSnapshot = "Back-to-School Credit", TopupAmountSnapshot = 115m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(4), CreatedBy = 2 },
                new TopupExecution { Id = 5, ExecutionCode = "TOPUP-RUN-005", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 5, IdempotencyKey = "topup-run-005", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 125m, TopupNameSnapshot = "Monthly Attendance Support", TopupAmountSnapshot = 125m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(5), CreatedBy = 2 },
                new TopupExecution { Id = 6, ExecutionCode = "TOPUP-RUN-006", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-006", ManualAmount = 135m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 135m, TopupNameSnapshot = "Manual Transport Reimbursement", TopupAmountSnapshot = 135m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(6), CreatedBy = 2 },
                new TopupExecution { Id = 7, ExecutionCode = "TOPUP-RUN-007", SourceType = TopupExecutionSourceType.System, SystemTopupId = 7, ScheduleTopUpId = null, IdempotencyKey = "topup-run-007", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 145m, TopupNameSnapshot = "STEM Enrichment Credit", TopupAmountSnapshot = 145m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(7), CreatedBy = 2 },
                new TopupExecution { Id = 8, ExecutionCode = "TOPUP-RUN-008", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 8, IdempotencyKey = "topup-run-008", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Executing, TotalTargetCount = 1, SuccessCount = 0, FailedCount = 1, TotalExecutedAmount = 0m, TopupNameSnapshot = "Monthly Commuter Credit", TopupAmountSnapshot = 155m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(8), CreatedBy = 2 },
                new TopupExecution { Id = 9, ExecutionCode = "TOPUP-RUN-009", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-009", ManualAmount = 165m, ManualReason = "Manual support credit adjustment", Status = TopupExecutionStatus.Completed, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 165m, TopupNameSnapshot = "Manual Materials Reimbursement", TopupAmountSnapshot = 165m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(9), CreatedBy = 2 },
                new TopupExecution { Id = 10, ExecutionCode = "TOPUP-RUN-010", SourceType = TopupExecutionSourceType.System, SystemTopupId = 10, ScheduleTopUpId = null, IdempotencyKey = "topup-run-010", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Pending, TotalTargetCount = 1, SuccessCount = 1, FailedCount = 0, TotalExecutedAmount = 175m, TopupNameSnapshot = "Holiday Programme Support", TopupAmountSnapshot = 175m, ConditionsSnapshot = "Matched active eligibility conditions", CreatedAt = createdAt.AddDays(10), CreatedBy = 2 },
                new TopupExecution { Id = 11, ExecutionCode = "TOPUP-RUN-011", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 1, IdempotencyKey = "topup-run-011", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Completed, TotalTargetCount = 374, SuccessCount = 372, FailedCount = 2, TotalExecutedAmount = 37200m, TopupNameSnapshot = "July Intake Welcome Credit", TopupAmountSnapshot = 65m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 6, 26, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 12, ExecutionCode = "TOPUP-RUN-012", SourceType = TopupExecutionSourceType.System, SystemTopupId = 5, ScheduleTopUpId = null, IdempotencyKey = "topup-run-012", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Completed, TotalTargetCount = 195, SuccessCount = 192, FailedCount = 3, TotalExecutedAmount = 42240m, TopupNameSnapshot = "Exam Preparation Support", TopupAmountSnapshot = 180m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 6, 27, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 13, ExecutionCode = "TOPUP-RUN-013", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-013", ManualAmount = 400m, ManualReason = "Manual support batch for dashboard seed", Status = TopupExecutionStatus.Completed, TotalTargetCount = 76, SuccessCount = 75, FailedCount = 1, TotalExecutedAmount = 39000m, TopupNameSnapshot = "Manual Support Batch", TopupAmountSnapshot = 400m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 6, 28, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 14, ExecutionCode = "TOPUP-RUN-014", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 4, IdempotencyKey = "topup-run-014", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Completed, TotalTargetCount = 438, SuccessCount = 434, FailedCount = 4, TotalExecutedAmount = 52080m, TopupNameSnapshot = "Orientation Transport Credit", TopupAmountSnapshot = 110m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 6, 29, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 15, ExecutionCode = "TOPUP-RUN-015", SourceType = TopupExecutionSourceType.System, SystemTopupId = 7, ScheduleTopUpId = null, IdempotencyKey = "topup-run-015", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Completed, TotalTargetCount = 181, SuccessCount = 179, FailedCount = 2, TotalExecutedAmount = 46540m, TopupNameSnapshot = "STEM Enrichment Credit", TopupAmountSnapshot = 220m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 6, 30, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 16, ExecutionCode = "TOPUP-RUN-016", SourceType = TopupExecutionSourceType.Manual, SystemTopupId = null, ScheduleTopUpId = null, IdempotencyKey = "topup-run-016", ManualAmount = 420m, ManualReason = "Manual targeted assistance batch for dashboard seed", Status = TopupExecutionStatus.Completed, TotalTargetCount = 120, SuccessCount = 115, FailedCount = 5, TotalExecutedAmount = 57500m, TopupNameSnapshot = "Manual Targeted Assistance", TopupAmountSnapshot = 420m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 7, 1, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 },
                new TopupExecution { Id = 17, ExecutionCode = "TOPUP-RUN-017", SourceType = TopupExecutionSourceType.Schedule, SystemTopupId = null, ScheduleTopUpId = 10, IdempotencyKey = "topup-run-017", ManualAmount = null, ManualReason = null, Status = TopupExecutionStatus.Completed, TotalTargetCount = 267, SuccessCount = 264, FailedCount = 3, TotalExecutedAmount = 68640m, TopupNameSnapshot = "Workshop Participation Credit", TopupAmountSnapshot = 200m, ConditionsSnapshot = "Dashboard seed batch for finance top-up trend", CreatedAt = new DateTime(2026, 7, 2, 2, 0, 0, DateTimeKind.Utc), CreatedBy = 2 });

            return modelBuilder;
        }
    }
}
