// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.SqlServer;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608095312_A")]
    partial class A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActorFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("ActorUserIdText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Object")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ActorUserIdText");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Object");

                    b.HasIndex("Category", "Action", "CreatedAt");

                    b.ToTable("AuditLog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = 4,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "AuthAccount:1:admin"
                        },
                        new
                        {
                            Id = 2,
                            Action = 100,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "AuthAccount:2:tenant.user"
                        },
                        new
                        {
                            Id = 3,
                            Action = 200,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "MfaSetting:1"
                        },
                        new
                        {
                            Id = 4,
                            Action = 202,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "EmailWhitelist:10"
                        },
                        new
                        {
                            Id = 5,
                            Action = 300,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "Product:10:MOS Audit"
                        },
                        new
                        {
                            Id = 6,
                            Action = 400,
                            ActorFullName = "Binh Tran",
                            ActorUserId = 2,
                            ActorUserIdText = "tenant.user",
                            Category = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "Product:2:MOS Admin"
                        },
                        new
                        {
                            Id = 7,
                            Action = 500,
                            ActorFullName = "An Nguyen",
                            ActorUserId = 1,
                            ActorUserIdText = "admin",
                            Category = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Object = "AuditLog:Pagination"
                        });
                });

            modelBuilder.Entity("Models.AuthAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserIdText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("UserIdText")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"UserIdText\" IS NOT NULL");

                    b.ToTable("AuthAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phuckhang1088@gmail.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            PasswordHash = "$2a$12$S8UUGws0L8l3mowPuKUsiOMNSgSQR4k9Jzic1gRdvXVKDTUvpxYty",
                            Status = 1,
                            UserIdText = "Sterling"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "binh.tran@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-002"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chau.le@example.com",
                            FailedLoginCount = 1,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-003"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dung.pham@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-004"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "giang.hoang@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-005"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hai.dang@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 2,
                            UserIdText = "user-006"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lan.bui@example.com",
                            FailedLoginCount = 2,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-007"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "minh.vo@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-008"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngan.do@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 1,
                            UserIdText = "user-009"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phuc.ngo@example.com",
                            FailedLoginCount = 0,
                            IsDeleted = false,
                            Status = 2,
                            UserIdText = "user-010"
                        });
                });

            modelBuilder.Entity("Models.EmailWhitelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Value\" IS NOT NULL");

                    b.ToTable("EmailWhitelist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "avepoint.com"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "example.com"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "admin@example.com"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "manager@example.com"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "support@example.com"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "partner.example.com"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "security@example.com"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "ops@example.com"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "contoso.com"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Value = "phuckhang1088@gmail.com"
                        });
                });

            modelBuilder.Entity("Models.EmailWhitelistSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailWhitelistSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsEnabled = false
                        });
                });

            modelBuilder.Entity("Models.MfaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MfaSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailEnabled = false,
                            IsDeleted = false,
                            IsEnabled = false,
                            SmsEnabled = false
                        });
                });

            modelBuilder.Entity("Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId");

                    b.HasIndex("DeliveryMethod");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InvalidatedAt");

                    b.HasIndex("Purpose");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"SessionId\" IS NOT NULL");

                    b.HasIndex("Target");

                    b.HasIndex("UsedAt");

                    b.ToTable("OtpVerification");
                });

            modelBuilder.Entity("Models.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasFilter("\"TokenHash\" IS NOT NULL");

                    b.HasIndex("UsedAt");

                    b.ToTable("PasswordResetToken");
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer access portal",
                            IsDeleted = false,
                            Name = "MOS Portal",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative management console",
                            IsDeleted = false,
                            Name = "MOS Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Analytics and reporting workspace",
                            IsDeleted = false,
                            Name = "MOS Analytics",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Billing and subscription management",
                            IsDeleted = false,
                            Name = "MOS Billing",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Support ticket management",
                            IsDeleted = false,
                            Name = "MOS Support",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Identity and access management",
                            IsDeleted = false,
                            Name = "MOS Identity",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document management workspace",
                            IsDeleted = false,
                            Name = "MOS Docs",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Workflow automation module",
                            IsDeleted = false,
                            Name = "MOS Workflow",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scheduled reporting module",
                            IsDeleted = false,
                            Name = "MOS Reports",
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Audit trail review module",
                            IsDeleted = false,
                            Name = "MOS Audit",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedByRefreshTokenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("StaySignedIn")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByRefreshTokenId");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasFilter("\"TokenHash\" IS NOT NULL");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "TenantUser"
                        });
                });

            modelBuilder.Entity("Models.SocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEmail");

                    b.HasIndex("AuthAccountId", "Provider")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("SocialLogin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthAccountId = 1,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 1,
                            ProviderEmail = "an.nguyen@example.com",
                            ProviderUserId = "google-user-001"
                        },
                        new
                        {
                            Id = 2,
                            AuthAccountId = 2,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 1,
                            ProviderEmail = "binh.tran@example.com",
                            ProviderUserId = "google-user-002"
                        },
                        new
                        {
                            Id = 3,
                            AuthAccountId = 3,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 2,
                            ProviderEmail = "chau.le@example.com",
                            ProviderUserId = "ms-user-003"
                        },
                        new
                        {
                            Id = 4,
                            AuthAccountId = 4,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 3,
                            ProviderEmail = "dung.pham@example.com",
                            ProviderUserId = "fb-user-004"
                        },
                        new
                        {
                            Id = 5,
                            AuthAccountId = 5,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 1,
                            ProviderEmail = "giang.hoang@example.com",
                            ProviderUserId = "google-user-005"
                        },
                        new
                        {
                            Id = 6,
                            AuthAccountId = 6,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 2,
                            ProviderEmail = "hai.dang@example.com",
                            ProviderUserId = "ms-user-006"
                        },
                        new
                        {
                            Id = 7,
                            AuthAccountId = 7,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 1,
                            ProviderEmail = "lan.bui@example.com",
                            ProviderUserId = "google-user-007"
                        },
                        new
                        {
                            Id = 8,
                            AuthAccountId = 8,
                            EmailVerified = false,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 3,
                            ProviderEmail = "minh.vo@example.com",
                            ProviderUserId = "fb-user-008"
                        },
                        new
                        {
                            Id = 9,
                            AuthAccountId = 9,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 2,
                            ProviderEmail = "ngan.do@example.com",
                            ProviderUserId = "ms-user-009"
                        },
                        new
                        {
                            Id = 10,
                            AuthAccountId = 10,
                            EmailVerified = true,
                            LinkedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = 1,
                            ProviderEmail = "phuc.ngo@example.com",
                            ProviderUserId = "google-user-010"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"AuthAccountId\" IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"PhoneNumber\" IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthAccountId = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nguyen Van An",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "+84901234567"
                        },
                        new
                        {
                            Id = 2,
                            AuthAccountId = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Tran Thi Binh",
                            Gender = 3,
                            IsDeleted = false,
                            PhoneNumber = "+84901234568"
                        },
                        new
                        {
                            Id = 3,
                            AuthAccountId = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Le Minh Chau",
                            Gender = 4,
                            IsDeleted = false,
                            PhoneNumber = "+84901234569"
                        },
                        new
                        {
                            Id = 4,
                            AuthAccountId = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Pham Quoc Dung",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "+84901234570"
                        },
                        new
                        {
                            Id = 5,
                            AuthAccountId = 5,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Hoang Mai Giang",
                            Gender = 3,
                            IsDeleted = false,
                            PhoneNumber = "+84901234571"
                        },
                        new
                        {
                            Id = 6,
                            AuthAccountId = 6,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Dang Thanh Hai",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "+84901234572"
                        },
                        new
                        {
                            Id = 7,
                            AuthAccountId = 7,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Bui Ngoc Lan",
                            Gender = 3,
                            IsDeleted = false,
                            PhoneNumber = "+84901234573"
                        },
                        new
                        {
                            Id = 8,
                            AuthAccountId = 8,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Vo Anh Minh",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "+84901234574"
                        },
                        new
                        {
                            Id = 9,
                            AuthAccountId = 9,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Do Thuy Ngan",
                            Gender = 3,
                            IsDeleted = false,
                            PhoneNumber = "+84901234575"
                        },
                        new
                        {
                            Id = 10,
                            AuthAccountId = 10,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Ngo Duc Phuc",
                            Gender = 2,
                            IsDeleted = false,
                            PhoneNumber = "+84901234576"
                        });
                });

            modelBuilder.Entity("Models.UserFavoriteProduct", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserFavoriteProduct");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            UserId = 3,
                            ProductId = 3
                        },
                        new
                        {
                            UserId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            UserId = 5,
                            ProductId = 5
                        },
                        new
                        {
                            UserId = 6,
                            ProductId = 6
                        },
                        new
                        {
                            UserId = 7,
                            ProductId = 7
                        },
                        new
                        {
                            UserId = 8,
                            ProductId = 8
                        },
                        new
                        {
                            UserId = 9,
                            ProductId = 10
                        },
                        new
                        {
                            UserId = 10,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("Models.UserProductAssignment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RoleInProduct")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProductAssignment");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            ProductId = 1,
                            RoleInProduct = 1
                        },
                        new
                        {
                            UserId = 4,
                            ProductId = 2,
                            RoleInProduct = 2
                        },
                        new
                        {
                            UserId = 5,
                            ProductId = 3,
                            RoleInProduct = 3
                        },
                        new
                        {
                            UserId = 6,
                            ProductId = 4,
                            RoleInProduct = 1
                        },
                        new
                        {
                            UserId = 8,
                            ProductId = 5,
                            RoleInProduct = 2
                        },
                        new
                        {
                            UserId = 9,
                            ProductId = 10,
                            RoleInProduct = 3
                        },
                        new
                        {
                            UserId = 10,
                            ProductId = 1,
                            RoleInProduct = 1
                        });
                });

            modelBuilder.Entity("Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Models.AuditLog", b =>
                {
                    b.HasOne("Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Models.OtpVerification", b =>
                {
                    b.HasOne("Models.AuthAccount", "AuthAccount")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Models.PasswordResetToken", b =>
                {
                    b.HasOne("Models.AuthAccount", "AuthAccount")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Models.RefreshToken", b =>
                {
                    b.HasOne("Models.AuthAccount", "AuthAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.RefreshToken", "ReplacedByRefreshToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByRefreshTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthAccount");

                    b.Navigation("ReplacedByRefreshToken");
                });

            modelBuilder.Entity("Models.SocialLogin", b =>
                {
                    b.HasOne("Models.AuthAccount", "AuthAccount")
                        .WithMany("SocialLogins")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.HasOne("Models.AuthAccount", "AuthAccount")
                        .WithOne("User")
                        .HasForeignKey("Models.User", "AuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("Models.UserFavoriteProduct", b =>
                {
                    b.HasOne("Models.Product", "Product")
                        .WithMany("UserFavoriteProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("UserFavoriteProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserProductAssignment", b =>
                {
                    b.HasOne("Models.Product", "Product")
                        .WithMany("UserProductAssignments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("UserProductAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserRole", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.AuthAccount", b =>
                {
                    b.Navigation("OtpVerifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SocialLogins");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Navigation("UserFavoriteProducts");

                    b.Navigation("UserProductAssignments");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("UserFavoriteProducts");

                    b.Navigation("UserProductAssignments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
